import type { RoutePlan, RouteVersion, RouteSnapshot, RoutePlanStatus, Waypoint, RouteSegment, TravelLeg, TravelConstraint, OptimizationResult } from "@/types/routeOptimization";
import type { ExecutionPriority } from "@/types/executionPackage";
import type { KnowledgeNodeRef } from "@/types/knowledgeGraph";
import { type DataResult, ok, fail } from "@/lib/data/result";
import { generateId, nowIso } from "@/lib/data/utils";

/**
 * v2.0 Checkpoint 30 — Route Plan persistence. A `RoutePlan` is one
 * aggregate document — its `versions[]` live inline, each carrying its
 * own frozen `RouteSnapshot` — the exact "whole graph as one document,
 * Package/Version/Snapshot" precedent `ExecutionPackage` established.
 */
let plans: RoutePlan[] = [];

export function resetRouteOptimizationStore(): void {
  plans = [];
}

export interface CreateRoutePlanInput {
  /** Pre-generated by the caller (`routeOptimizationActions.ts`) — `buildRouteStructure` (the Route Builder core engine) needs the plan's own id to stamp onto every waypoint/segment/leg's `route_plan_id` field before the plan itself exists, the exact "seed built first, id threaded through" sequencing `DispatchAssignmentSeed` established before it. */
  id: string;
  dispatch_order_id: string;
  dispatch_assignment_id: string;
  execution_package_id: string;
  execution_version_id: string;
  operational_plan_id: string | null;
  priority: ExecutionPriority;
  context: KnowledgeNodeRef | null;
  waypoints: Waypoint[];
  segments: RouteSegment[];
  travel_legs: TravelLeg[];
  constraints: TravelConstraint[];
}

async function listRoutePlansForWorkspace(workspaceId: string, includeArchived = false): Promise<RoutePlan[]> {
  return plans.filter((p) => p.workspace_id === workspaceId && (includeArchived || p.status !== "archived"));
}

async function getRoutePlanById(id: string): Promise<RoutePlan | null> {
  return plans.find((p) => p.id === id) ?? null;
}

function buildSnapshot(input: Pick<CreateRoutePlanInput, "waypoints" | "segments" | "travel_legs" | "constraints">, optimizationResult: OptimizationResult | null): RouteSnapshot {
  return {
    id: generateId("route_snapshot"),
    captured_at: nowIso(),
    waypoints: input.waypoints,
    segments: input.segments,
    travel_legs: input.travel_legs,
    constraints: input.constraints,
    optimization_result: optimizationResult,
  };
}

async function createRoutePlan(workspaceId: string, createdBy: string, input: CreateRoutePlanInput): Promise<DataResult<RoutePlan>> {
  const timestamp = nowIso();
  const planId = input.id;
  const initialVersion: RouteVersion = {
    id: generateId("route_version"),
    route_plan_id: planId,
    version_number: 1,
    snapshot: buildSnapshot(input, null),
    created_at: timestamp,
  };

  const created: RoutePlan = {
    id: planId,
    workspace_id: workspaceId,
    dispatch_order_id: input.dispatch_order_id,
    dispatch_assignment_id: input.dispatch_assignment_id,
    execution_package_id: input.execution_package_id,
    execution_version_id: input.execution_version_id,
    operational_plan_id: input.operational_plan_id,
    priority: input.priority,
    context: input.context,
    status: "draft",
    versions: [initialVersion],
    created_by: createdBy,
    created_at: timestamp,
    updated_at: timestamp,
    archived_at: null,
  };
  plans = [...plans, created];
  return ok(created);
}

async function setRoutePlanStatus(id: string, workspaceId: string, status: RoutePlanStatus): Promise<DataResult<RoutePlan>> {
  const existing = plans.find((p) => p.id === id && p.workspace_id === workspaceId);
  if (!existing) return fail("This route plan could not be found.");

  const timestamp = nowIso();
  const updated: RoutePlan = { ...existing, status, updated_at: timestamp, archived_at: status === "archived" ? timestamp : existing.archived_at };
  plans = plans.map((p) => (p.id === id ? updated : p));
  return ok(updated);
}

export interface AppendOptimizedVersionInput {
  waypoints: Waypoint[];
  segments: RouteSegment[];
  travel_legs: TravelLeg[];
  optimization_result: OptimizationResult;
}

/** Appends a fresh, immutable `RouteVersion` carrying the Optimization Engine's own reordered waypoints/segments/travel legs (the same declared constraints as the plan's current version, untouched — optimization never changes what was declared, only the stop order) — the "Optimization Recalculated"/"Route Optimized" event never mutates a prior version's own frozen snapshot in place. */
async function appendOptimizedVersion(routePlanId: string, workspaceId: string, input: AppendOptimizedVersionInput): Promise<DataResult<RoutePlan>> {
  const existing = plans.find((p) => p.id === routePlanId && p.workspace_id === workspaceId);
  if (!existing) return fail("This route plan could not be found.");

  const current = existing.versions[existing.versions.length - 1];
  const timestamp = nowIso();
  const nextVersion: RouteVersion = {
    id: generateId("route_version"),
    route_plan_id: routePlanId,
    version_number: current.version_number + 1,
    snapshot: { id: generateId("route_snapshot"), captured_at: timestamp, waypoints: input.waypoints, segments: input.segments, travel_legs: input.travel_legs, constraints: current.snapshot.constraints, optimization_result: input.optimization_result },
    created_at: timestamp,
  };

  const updated: RoutePlan = { ...existing, versions: [...existing.versions, nextVersion], updated_at: timestamp };
  plans = plans.map((p) => (p.id === routePlanId ? updated : p));
  return ok(updated);
}

export interface RouteOptimizationRepository {
  listRoutePlansForWorkspace: typeof listRoutePlansForWorkspace;
  getRoutePlanById: typeof getRoutePlanById;
  createRoutePlan: typeof createRoutePlan;
  setRoutePlanStatus: typeof setRoutePlanStatus;
  appendOptimizedVersion: typeof appendOptimizedVersion;
}

export const mockRouteOptimizationRepository: RouteOptimizationRepository = {
  listRoutePlansForWorkspace,
  getRoutePlanById,
  createRoutePlan,
  setRoutePlanStatus,
  appendOptimizedVersion,
};
