import { EVENT_SERVICE_STATUSES, type EventServiceStatus } from "@/core/enums/eventServiceStatus";
import { sumMinor } from "@/lib/money";
import type { Service } from "@/types/service";
import type { ServiceVersion } from "@/types/serviceVersion";
import type { ServiceAddOn } from "@/types/serviceAddOn";
import type { ServiceChecklistTemplateItem } from "@/types/serviceChecklistTemplateItem";
import type { ServiceTimelineTemplateItem } from "@/types/serviceTimelineTemplateItem";
import type { ServiceInventoryTemplateItem } from "@/types/serviceInventoryTemplateItem";
import type { ServicePurchaseTemplateItem } from "@/types/servicePurchaseTemplateItem";
import type { ServiceBudgetTemplateLine } from "@/types/serviceBudgetTemplateLine";
import type { ServiceTeamRoleRequirement } from "@/types/serviceTeamRoleRequirement";
import type { ServiceVendorSuggestion } from "@/types/serviceVendorSuggestion";
import type { ChecklistItemTemplateSnapshot } from "@/types/checklistItem";
import type { EventScheduleItemTemplateSnapshot } from "@/types/eventScheduleItem";
import type { ChecklistCategory } from "@/core/enums/checklistCategory";
import type { NotePriority } from "@/core/enums/notePriority";
import type { ScheduleCategory } from "@/core/enums/scheduleCategory";

export { EVENT_SERVICE_STATUSES };
export type { EventServiceStatus };

/**
 * The lifecycle of one Service booked on one Event — independent of both
 * the catalog Service's own status and the Event's own status/lifecycle
 * stage. "cancelled" is a real terminal member (matching every other
 * module's status enum) rather than a deletion — cancelling an EventService
 * never removes it or the rows it already generated.
 */
const EVENT_SERVICE_TRANSITIONS: Record<EventServiceStatus, EventServiceStatus[]> = {
  proposed: ["confirmed", "cancelled"],
  confirmed: ["in_progress", "cancelled"],
  in_progress: ["completed", "cancelled"],
  completed: [],
  cancelled: [],
};

export function canTransitionEventServiceStatus(from: EventServiceStatus, to: EventServiceStatus): boolean {
  if (from === to) return false;
  return EVENT_SERVICE_TRANSITIONS[from].includes(to);
}

/**
 * The live `name`/`price_minor` overrides may be edited any time before the
 * booking reaches a terminal status — once `completed` or `cancelled`, the
 * record represents a finished/dead booking whose price and name should
 * stop moving, the same "terminal states lock down" rule
 * `EVENT_SERVICE_TRANSITIONS` already enforces for status itself.
 */
export function canOverrideEventService(status: EventServiceStatus): boolean {
  return status !== "completed" && status !== "cancelled";
}

/**
 * The definition of "usage" the Services Catalog/Health/Search surfaces all
 * share: how many EventServices currently represent real, non-cancelled
 * demand for a catalog Service. A `cancelled` EventService is excluded —
 * it's a booking that fell through, not evidence the Service is in use.
 * `completed` counts (a finished booking is still real historical usage).
 * `EVENT_SERVICE_TRANSITIONS` guarantees `cancelled` is reachable only from
 * a non-terminal status and never left once reached, so this predicate
 * alone is enough to know whether transitioning an EventService's status
 * could ever change a Service's usage count (see
 * useTransitionEventServiceStatus's own invalidation logic).
 */
export function countsTowardServiceUsage(status: EventServiceStatus): boolean {
  return status !== "cancelled";
}

/** A "pending" ChecklistItem or "planned" EventScheduleItem generated by an EventService is safe to delete outright if the EventService is removed — anything further along represents real work already done, and is preserved rather than silently destroyed. Matches the architecture review's explicit "never silently destroy work" recommendation. */
export function isGeneratedChecklistItemRemovable(status: string): boolean {
  return status === "pending";
}

export function isGeneratedScheduleItemRemovable(status: string): boolean {
  return status === "planned";
}

/** offset_minutes may be negative (before the event's own start) or positive (after) — resolveOffsetTime tolerates both. Returns null whenever eventStartTime isn't a well-formed "HH:MM" string, rather than throwing — a Service can still be assigned to an Event with no time set yet. */
function parseTimeToMinutes(time: string | null): number | null {
  if (!time) return null;
  const match = /^(\d{1,2}):(\d{2})$/.exec(time.trim());
  if (!match) return null;
  const hours = Number(match[1]);
  const minutes = Number(match[2]);
  if (hours > 23 || minutes > 59) return null;
  return hours * 60 + minutes;
}

function formatMinutesToTime(totalMinutes: number): string {
  const normalized = ((totalMinutes % 1440) + 1440) % 1440;
  const hours = Math.floor(normalized / 60);
  const minutes = normalized % 60;
  return `${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}`;
}

export function resolveOffsetTime(eventStartTime: string | null, offsetMinutes: number): string | null {
  const baseMinutes = parseTimeToMinutes(eventStartTime);
  if (baseMinutes === null) return null;
  return formatMinutesToTime(baseMinutes + offsetMinutes);
}

/** due_offset_days counts days BEFORE the Event date a checklist item is due (a positive value is earlier, matching how staff naturally describe deadlines — "3 days before the event"). Returns null whenever eventDate is unset, or offsetDays is null (no deadline at all). */
export function resolveOffsetDueDate(eventDate: string | null, offsetDays: number | null): string | null {
  if (!eventDate || offsetDays === null) return null;
  const parsed = new Date(`${eventDate}T00:00:00`);
  if (Number.isNaN(parsed.getTime())) return null;
  parsed.setDate(parsed.getDate() - offsetDays);
  return parsed.toISOString().slice(0, 10);
}

export interface EventServiceAssignmentContext {
  eventDate: string | null;
  eventStartTime: string | null;
  selectedAddOnIds?: string[];
}

export interface EventServiceAssignmentInput {
  service: Pick<Service, "id" | "name">;
  /** `name_snapshot` is guaranteed non-null here — only a "published" ServiceVersion is ever assignable (see canAssignService), and publishServiceVersion always populates it. Falls back to the Service's own current name only as a defensive guard, never expected to trigger in practice. */
  version: Pick<ServiceVersion, "id" | "name_snapshot" | "base_price_minor" | "currency">;
  addOns: ServiceAddOn[];
  checklistTemplateItems: ServiceChecklistTemplateItem[];
  timelineTemplateItems: ServiceTimelineTemplateItem[];
  inventoryTemplateItems: ServiceInventoryTemplateItem[];
  purchaseTemplateItems: ServicePurchaseTemplateItem[];
  budgetTemplateLines: ServiceBudgetTemplateLine[];
  teamRoleRequirements: ServiceTeamRoleRequirement[];
  vendorSuggestions: ServiceVendorSuggestion[];
}

export interface GeneratedChecklistItemSpec {
  title: string;
  category: ChecklistCategory;
  priority: NotePriority;
  due_date: string | null;
  template_snapshot: ChecklistItemTemplateSnapshot;
}

export interface GeneratedScheduleItemSpec {
  title: string;
  category: ScheduleCategory;
  start_time: string | null;
  end_time: string | null;
  template_snapshot: EventScheduleItemTemplateSnapshot;
}

export interface GeneratedInventoryRequirementSpec {
  inventory_item_id: string | null;
  item_name: string;
  quantity: number;
}

export interface GeneratedPurchaseRequirementSpec {
  item_name: string;
  estimated_unit_cost_minor: number;
  estimated_quantity: number;
  typical_vendor_id: string | null;
}

export interface GeneratedBudgetLineSpec {
  label: string;
  category: string | null;
  estimated_revenue_minor: number;
  estimated_cost_minor: number;
}

export interface GeneratedTeamRequirementSpec {
  role_label: string;
  quantity: number;
  note: string | null;
}

export interface GeneratedVendorAssignmentSpec {
  vendor_id: string;
  note: string | null;
}

export interface EventServiceAssignmentPlan {
  name: string;
  name_template_value: string;
  price_minor: number;
  price_template_value: number;
  currency: string;
  selected_add_on_ids: string[];
  checklistItems: GeneratedChecklistItemSpec[];
  scheduleItems: GeneratedScheduleItemSpec[];
  inventoryRequirements: GeneratedInventoryRequirementSpec[];
  purchaseRequirements: GeneratedPurchaseRequirementSpec[];
  budgetLines: GeneratedBudgetLineSpec[];
  teamRequirements: GeneratedTeamRequirementSpec[];
  vendorAssignments: GeneratedVendorAssignmentSpec[];
}

/**
 * The base price plus whichever add-ons were actually selected — extracted
 * as its own pure function (rather than inlined in the assignment plan) so
 * a future consumer that needs a price preview WITHOUT a full Event context
 * — Proposal Builder, most notably, per the pre-migration domain review's
 * §10 finding — can call this directly instead of faking one.
 */
export function computeServicePrice(basePriceMinor: number, addOns: ServiceAddOn[], selectedAddOnIds: string[]): number {
  const selectedAddOns = addOns.filter((addOn) => selectedAddOnIds.includes(addOn.id));
  return sumMinor([basePriceMinor, ...selectedAddOns.map((addOn) => addOn.price_delta_minor)]);
}

export interface ServiceRequirementsInput {
  inventoryTemplateItems: ServiceInventoryTemplateItem[];
  purchaseTemplateItems: ServicePurchaseTemplateItem[];
  budgetTemplateLines: ServiceBudgetTemplateLine[];
  teamRoleRequirements: ServiceTeamRoleRequirement[];
  vendorSuggestions: ServiceVendorSuggestion[];
}

export interface ServiceRequirementsPlan {
  inventoryRequirements: GeneratedInventoryRequirementSpec[];
  purchaseRequirements: GeneratedPurchaseRequirementSpec[];
  budgetLines: GeneratedBudgetLineSpec[];
  teamRequirements: GeneratedTeamRequirementSpec[];
  vendorAssignments: GeneratedVendorAssignmentSpec[];
}

/**
 * Maps every requirement/estimate template category straight across into
 * its generated Instance-layer shape — unlike checklist/timeline items,
 * none of these need offset resolution against the Event's date/time, so
 * this is a genuine 1:1 copy, extracted as its own pure function for the
 * same reason computeServicePrice was: an isolated, independently testable
 * and independently reusable step, not something only reachable by running
 * the full assignment plan.
 */
export function computeServiceRequirements(input: ServiceRequirementsInput): ServiceRequirementsPlan {
  const inventoryRequirements: GeneratedInventoryRequirementSpec[] = input.inventoryTemplateItems.map((item) => ({
    inventory_item_id: item.inventory_item_id,
    item_name: item.item_name,
    quantity: item.quantity,
  }));

  const purchaseRequirements: GeneratedPurchaseRequirementSpec[] = input.purchaseTemplateItems.map((item) => ({
    item_name: item.item_name,
    estimated_unit_cost_minor: item.estimated_unit_cost_minor,
    estimated_quantity: item.estimated_quantity,
    typical_vendor_id: item.typical_vendor_id,
  }));

  const budgetLines: GeneratedBudgetLineSpec[] = input.budgetTemplateLines.map((line) => ({
    label: line.label,
    category: line.category,
    estimated_revenue_minor: line.estimated_revenue_minor,
    estimated_cost_minor: line.estimated_cost_minor,
  }));

  const teamRequirements: GeneratedTeamRequirementSpec[] = input.teamRoleRequirements.map((role) => ({
    role_label: role.role_label,
    quantity: role.quantity,
    note: role.note,
  }));

  const vendorAssignments: GeneratedVendorAssignmentSpec[] = input.vendorSuggestions.map((suggestion) => ({
    vendor_id: suggestion.vendor_id,
    note: suggestion.note,
  }));

  return { inventoryRequirements, purchaseRequirements, budgetLines, teamRequirements, vendorAssignments };
}

/**
 * The single source of truth for what assigning a Service to an Event
 * generates — orchestration only. Every real computation lives in a named
 * pure function it calls (computeServicePrice, computeServiceRequirements,
 * plus the checklist/timeline mapping below, each already delegating its
 * own date/time math to resolveOffsetDueDate/resolveOffsetTime); this
 * function's only job is gathering their results into one plan. Both
 * ServicesRepository.mockRepository AND the future Supabase
 * `assign_service_to_event` RPC must produce exactly this same set of rows;
 * neither repository re-derives this logic independently (the same
 * "TypeScript workflow is the source of truth, SQL is its equivalent" rule
 * `derivePurchaseReceiptStatus`/`getInventoryMovementDelta` already
 * establish elsewhere in this codebase).
 *
 * Deliberately generates nothing for Finance or Inventory to act on
 * directly — every requirement row produced here is a draft/estimate a
 * human reviews before it becomes a real Purchase, Invoice, or Inventory
 * movement, per the architecture's "never auto-mutate a real ledger" rule.
 */
export function buildEventServiceAssignmentPlan(input: EventServiceAssignmentInput, context: EventServiceAssignmentContext): EventServiceAssignmentPlan {
  const selectedAddOnIds = context.selectedAddOnIds ?? [];
  const priceMinor = computeServicePrice(input.version.base_price_minor, input.addOns, selectedAddOnIds);
  const nameSnapshot = input.version.name_snapshot ?? input.service.name;

  // Sorted by display_order before mapping — mirrors the SQL RPC's `order by
  // display_order` exactly. Found and fixed during the pre-push migration
  // review: this function previously relied on whatever order its caller's
  // array happened to be in (harmless for the seeded mock data, since it
  // was already display_order-ordered, but a real parity gap against the
  // RPC for any Service whose template items were authored out of order).
  const checklistItems: GeneratedChecklistItemSpec[] = [...input.checklistTemplateItems]
    .sort((a, b) => a.display_order - b.display_order)
    .map((item) => {
      const dueDate = resolveOffsetDueDate(context.eventDate, item.due_offset_days);
      return {
        title: item.title,
        category: item.category,
        priority: item.priority,
        due_date: dueDate,
        template_snapshot: { title: item.title, category: item.category, priority: item.priority, due_date: dueDate },
      };
    });

  const scheduleItems: GeneratedScheduleItemSpec[] = [...input.timelineTemplateItems]
    .sort((a, b) => a.display_order - b.display_order)
    .map((item) => {
      const startTime = resolveOffsetTime(context.eventStartTime, item.offset_minutes_from_event_start);
      const endTime = startTime !== null && item.duration_minutes != null ? resolveOffsetTime(startTime, item.duration_minutes) : null;
      return {
        title: item.title,
        category: item.category,
        start_time: startTime,
        end_time: endTime,
        template_snapshot: { title: item.title, category: item.category, start_time: startTime, end_time: endTime },
      };
    });

  const requirements = computeServiceRequirements({
    inventoryTemplateItems: input.inventoryTemplateItems,
    purchaseTemplateItems: input.purchaseTemplateItems,
    budgetTemplateLines: input.budgetTemplateLines,
    teamRoleRequirements: input.teamRoleRequirements,
    vendorSuggestions: input.vendorSuggestions,
  });

  return {
    name: nameSnapshot,
    name_template_value: nameSnapshot,
    price_minor: priceMinor,
    price_template_value: priceMinor,
    currency: input.version.currency,
    selected_add_on_ids: selectedAddOnIds,
    checklistItems,
    scheduleItems,
    ...requirements,
  };
}
