import { registerMergeField } from "@/core/documents/mergeFieldRegistry";
import { registerMergeResolver } from "@/core/documents/mergeEngine";
import { getAutomation } from "@/core/automation/registry";
import type { MergeFieldDefinition } from "@/types/documentPlatform";

/**
 * The `"automation"` Merge Field domain (Step 4/13) — which real,
 * registered Automation triggered this Document's own generation, when
 * `context.automationId` is set (Step 13's own "Documents may be generated
 * by the Automation Engine"). `null` for a manually-generated Document —
 * never a fabricated "system" placeholder.
 */
export const automationMergeFieldDefinitions: MergeFieldDefinition[] = [
  { key: "generated_by_automation", label: "Generated By Automation", description: "The name of the Automation that triggered this Document's own generation, if any.", domain: "automation", valueType: "string", required: false },
];

export function registerAutomationMergeFields(): void {
  for (const definition of automationMergeFieldDefinitions) registerMergeField(definition);

  registerMergeResolver("generated_by_automation", async (context) => {
    if (!context.automationId) return null;
    return getAutomation(context.automationId)?.name ?? null;
  });
}
