import { registerMergeField } from "@/core/documents/mergeFieldRegistry";
import { registerMergeResolver } from "@/core/documents/mergeEngine";
import { resolveMemberSessionSnapshot } from "@/lib/auth/memberSessionSnapshot";
import { clockNow } from "@/core/time/clock";
import type { MergeFieldDefinition } from "@/types/documentPlatform";

/**
 * The `"user"` Merge Field domain (Step 4) — who is generating this
 * Document, and when. `generated_at` reads through `clockNow()` (never
 * `new Date()` directly) so a test can freeze it — the one field in this
 * domain that legitimately varies call to call; "Merge should be
 * deterministic" means no hidden randomness or AI calls, not that a
 * generation timestamp must be pinned.
 */
export const userMergeFieldDefinitions: MergeFieldDefinition[] = [
  { key: "generated_by_member", label: "Generated By", description: "The full name of the member who generated this Document.", domain: "user", valueType: "string", required: true },
  { key: "generated_by_email", label: "Generated By (Email)", description: "The email of the member who generated this Document.", domain: "user", valueType: "string", required: false },
  { key: "generated_at", label: "Generated At", description: "The date this Document was compiled.", domain: "user", valueType: "date", required: true },
];

export function registerUserMergeFields(): void {
  for (const definition of userMergeFieldDefinitions) registerMergeField(definition);

  registerMergeResolver("generated_by_member", async (context) => {
    const session = await resolveMemberSessionSnapshot();
    if (session.kind !== "active" || session.membership.id !== context.memberId) return null;
    return session.profile.full_name ?? session.user.email;
  });

  registerMergeResolver("generated_by_email", async (context) => {
    const session = await resolveMemberSessionSnapshot();
    if (session.kind !== "active" || session.membership.id !== context.memberId) return null;
    return session.user.email;
  });

  registerMergeResolver("generated_at", async () => {
    return clockNow().toISOString().slice(0, 10);
  });
}
