export const DOCUMENT_CATEGORIES = [
  "contract",
  "signed_contract",
  "exhibit",
  "proposal",
  "invoice",
  "receipt",
  "payment_confirmation",
  "expense_receipt",
  "reimbursement_proof",
  "moodboard",
  "inspiration",
  "floor_plan",
  "event_schedule",
  "checklist",
  "photo",
  "video",
  "identification",
  "insurance",
  "license",
  "tax",
  "policy",
  "waiver",
  "report",
  "internal",
  "other",
] as const;

export type DocumentCategory = (typeof DOCUMENT_CATEGORIES)[number];

export const DOCUMENT_CATEGORY_LABELS: Record<DocumentCategory, string> = {
  contract: "Contract",
  signed_contract: "Signed Contract",
  exhibit: "Exhibit",
  proposal: "Proposal",
  invoice: "Invoice",
  receipt: "Receipt",
  payment_confirmation: "Payment Confirmation",
  expense_receipt: "Expense Receipt",
  reimbursement_proof: "Reimbursement Proof",
  moodboard: "Moodboard",
  inspiration: "Inspiration",
  floor_plan: "Floor Plan",
  event_schedule: "Event Schedule",
  checklist: "Checklist",
  photo: "Photo",
  video: "Video",
  identification: "Identification",
  insurance: "Insurance",
  license: "License",
  tax: "Tax",
  policy: "Policy",
  waiver: "Waiver",
  report: "Report",
  internal: "Internal",
  other: "Other",
};

/** Documents seeded/uploaded with no real categorization yet — surfaced by the "Documents Missing Category" dashboard metric. */
export const UNCATEGORIZED_DOCUMENT_CATEGORIES: DocumentCategory[] = ["other"];
