export const EXPENSE_CATEGORIES = [
  "decor",
  "flowers",
  "rentals",
  "venue",
  "photography",
  "video",
  "food_beverage",
  "transportation",
  "printing",
  "supplies",
  "inventory",
  "team_payroll",
  "supplier_payment",
  "marketing",
  "software",
  "insurance",
  "taxes",
  "fees",
  "travel",
  "refund",
  "reimbursement",
  "miscellaneous",
] as const;

export type ExpenseCategory = (typeof EXPENSE_CATEGORIES)[number];

export const EXPENSE_CATEGORY_LABELS: Record<ExpenseCategory, string> = {
  decor: "Decor",
  flowers: "Flowers",
  rentals: "Rentals",
  venue: "Venue",
  photography: "Photography",
  video: "Video",
  food_beverage: "Food & Beverage",
  transportation: "Transportation",
  printing: "Printing",
  supplies: "Supplies",
  inventory: "Inventory",
  team_payroll: "Team Payroll",
  supplier_payment: "Supplier Payment",
  marketing: "Marketing",
  software: "Software",
  insurance: "Insurance",
  taxes: "Taxes",
  fees: "Fees",
  travel: "Travel",
  refund: "Refund",
  reimbursement: "Reimbursement",
  miscellaneous: "Miscellaneous",
};
