export const TIMELINE_ACTIVITY_TYPES = [
  "lead_created",
  "lead_updated",
  "status_changed",
  "note_added",
  "note_pinned",
  "note_unpinned",
  "welcome_guide_sent",
  "lead_archived",
  "lead_converted",
  "client_created",
  "client_updated",
  "tags_changed",
  "vip_status_changed",
  "communication_preference_changed",
  "client_archived",
  "client_restored",
  "event_created",
  "event_updated",
  "lifecycle_stage_changed",
  "priority_changed",
  "checklist_item_created",
  "checklist_item_completed",
  "checklist_template_applied",
  "schedule_item_created",
  "schedule_item_updated",
  "event_archived",
  "event_restored",
  "event_cancelled",
  "event_completed",
  "contract_created",
  "contract_updated",
  "contract_sent",
  "contract_viewed",
  "contract_signed",
  "contract_declined",
  "contract_cancelled",
  "contract_completed",
  "contract_archived",
  "contract_restored",
] as const;

export type TimelineActivityType = (typeof TIMELINE_ACTIVITY_TYPES)[number];

export const TIMELINE_ACTIVITY_LABELS: Record<TimelineActivityType, string> = {
  lead_created: "Lead created",
  lead_updated: "Lead information updated",
  status_changed: "Status changed",
  note_added: "Note added",
  note_pinned: "Note pinned",
  note_unpinned: "Note unpinned",
  welcome_guide_sent: "Welcome Guide sent",
  lead_archived: "Lead archived",
  lead_converted: "Lead converted to Client",
  client_created: "Client created",
  client_updated: "Client information updated",
  tags_changed: "Tags updated",
  vip_status_changed: "VIP status changed",
  communication_preference_changed: "Communication preference changed",
  client_archived: "Client archived",
  client_restored: "Client restored",
  event_created: "Event created",
  event_updated: "Event information updated",
  lifecycle_stage_changed: "Lifecycle stage changed",
  priority_changed: "Priority changed",
  checklist_item_created: "Checklist item created",
  checklist_item_completed: "Checklist item completed",
  checklist_template_applied: "Default checklist applied",
  schedule_item_created: "Schedule item created",
  schedule_item_updated: "Schedule item updated",
  event_archived: "Event archived",
  event_restored: "Event restored",
  event_cancelled: "Event cancelled",
  event_completed: "Event completed",
  contract_created: "Contract created",
  contract_updated: "Contract updated",
  contract_sent: "Contract sent",
  contract_viewed: "Contract viewed",
  contract_signed: "Contract signed",
  contract_declined: "Contract declined",
  contract_cancelled: "Contract cancelled",
  contract_completed: "Contract completed",
  contract_archived: "Contract archived",
  contract_restored: "Contract restored",
};
