export const TIMELINE_ACTIVITY_TYPES = [
  "lead_created",
  "lead_updated",
  "status_changed",
  "note_added",
  "note_pinned",
  "note_unpinned",
  "welcome_guide_sent",
  "lead_archived",
  "lead_converted",
  "client_created",
  "client_updated",
  "tags_changed",
  "vip_status_changed",
  "communication_preference_changed",
  "client_archived",
  "client_restored",
  "event_created",
  "event_updated",
  "lifecycle_stage_changed",
  "priority_changed",
  "checklist_item_created",
  "checklist_item_completed",
  "checklist_template_applied",
  "schedule_item_created",
  "schedule_item_updated",
  "event_archived",
  "event_restored",
  "event_cancelled",
  "event_completed",
  "contract_created",
  "contract_updated",
  "contract_sent",
  "contract_viewed",
  "contract_signed",
  "contract_declined",
  "contract_cancelled",
  "contract_completed",
  "contract_archived",
  "contract_restored",
  "invoice_created",
  "invoice_updated",
  "invoice_issued",
  "invoice_sent",
  "invoice_viewed",
  "invoice_partially_paid",
  "invoice_paid",
  "invoice_overdue",
  "invoice_voided",
  "invoice_archived",
  "invoice_restored",
  "payment_created",
  "payment_processing",
  "payment_succeeded",
  "payment_failed",
  "payment_refunded",
  "payment_cancelled",
  "expense_created",
  "expense_updated",
  "expense_approved",
  "expense_marked_due",
  "expense_paid",
  "expense_reimbursed",
  "expense_cancelled",
  "expense_archived",
  "expense_restored",
  "document_created",
  "document_metadata_updated",
  "document_version_created",
  "document_activated",
  "document_superseded",
  "document_expired",
  "document_archived",
  "document_restored",
  "document_soft_deleted",
  "document_visibility_changed",
  "document_moved_to_folder",
  "document_downloaded",
  "document_folder_created",
  "document_folder_renamed",
  "document_folder_moved",
  "document_folder_archived",
  "document_folder_restored",
  "document_folder_template_applied",
  "media_asset_uploaded",
  "media_asset_version_replaced",
  "media_asset_archived",
  "media_asset_restored",
] as const;

export type TimelineActivityType = (typeof TIMELINE_ACTIVITY_TYPES)[number];

export const TIMELINE_ACTIVITY_LABELS: Record<TimelineActivityType, string> = {
  lead_created: "Lead created",
  lead_updated: "Lead information updated",
  status_changed: "Status changed",
  note_added: "Note added",
  note_pinned: "Note pinned",
  note_unpinned: "Note unpinned",
  welcome_guide_sent: "Welcome Guide sent",
  lead_archived: "Lead archived",
  lead_converted: "Lead converted to Client",
  client_created: "Client created",
  client_updated: "Client information updated",
  tags_changed: "Tags updated",
  vip_status_changed: "VIP status changed",
  communication_preference_changed: "Communication preference changed",
  client_archived: "Client archived",
  client_restored: "Client restored",
  event_created: "Event created",
  event_updated: "Event information updated",
  lifecycle_stage_changed: "Lifecycle stage changed",
  priority_changed: "Priority changed",
  checklist_item_created: "Checklist item created",
  checklist_item_completed: "Checklist item completed",
  checklist_template_applied: "Default checklist applied",
  schedule_item_created: "Schedule item created",
  schedule_item_updated: "Schedule item updated",
  event_archived: "Event archived",
  event_restored: "Event restored",
  event_cancelled: "Event cancelled",
  event_completed: "Event completed",
  contract_created: "Contract created",
  contract_updated: "Contract updated",
  contract_sent: "Contract sent",
  contract_viewed: "Contract viewed",
  contract_signed: "Contract signed",
  contract_declined: "Contract declined",
  contract_cancelled: "Contract cancelled",
  contract_completed: "Contract completed",
  contract_archived: "Contract archived",
  contract_restored: "Contract restored",
  invoice_created: "Invoice created",
  invoice_updated: "Invoice updated",
  invoice_issued: "Invoice issued",
  invoice_sent: "Invoice sent",
  invoice_viewed: "Invoice viewed",
  invoice_partially_paid: "Invoice partially paid",
  invoice_paid: "Invoice paid",
  invoice_overdue: "Invoice overdue",
  invoice_voided: "Invoice voided",
  invoice_archived: "Invoice archived",
  invoice_restored: "Invoice restored",
  payment_created: "Payment created",
  payment_processing: "Payment processing",
  payment_succeeded: "Payment succeeded",
  payment_failed: "Payment failed",
  payment_refunded: "Payment refunded",
  payment_cancelled: "Payment cancelled",
  expense_created: "Expense created",
  expense_updated: "Expense updated",
  expense_approved: "Expense approved",
  expense_marked_due: "Expense marked due",
  expense_paid: "Expense paid",
  expense_reimbursed: "Expense reimbursed",
  expense_cancelled: "Expense cancelled",
  expense_archived: "Expense archived",
  expense_restored: "Expense restored",
  document_created: "Document uploaded",
  document_metadata_updated: "Document metadata updated",
  document_version_created: "New version uploaded",
  document_activated: "Document activated",
  document_superseded: "Document superseded by a newer version",
  document_expired: "Document expired",
  document_archived: "Document archived",
  document_restored: "Document restored",
  document_soft_deleted: "Document deleted",
  document_visibility_changed: "Document visibility changed",
  document_moved_to_folder: "Document moved to a different folder",
  document_downloaded: "Document downloaded",
  document_folder_created: "Folder created",
  document_folder_renamed: "Folder renamed",
  document_folder_moved: "Folder moved",
  document_folder_archived: "Folder archived",
  document_folder_restored: "Folder restored",
  document_folder_template_applied: "Default folder template applied",
  media_asset_uploaded: "File uploaded",
  media_asset_version_replaced: "File replaced with a new version",
  media_asset_archived: "File archived",
  media_asset_restored: "File restored",
};
