import { describe, expect, it, vi, beforeEach } from "vitest";

vi.mock("@/lib/data", () => ({
  getChecklistByEventId: vi.fn(),
}));

import { getEventServiceChecklistItems } from "@/lib/queries/services/eventServiceChecklist";
import { getChecklistByEventId } from "@/lib/data";

function checklistItem(overrides: Partial<Record<string, unknown>> = {}) {
  return {
    id: "item_1",
    workspace_id: "ws",
    owner_type: "event",
    owner_id: "event_1",
    title: "Confirm florals",
    description: null,
    category: "flowers",
    priority: "normal",
    status: "pending",
    due_date: null,
    completed_at: null,
    assigned_type: "none",
    assigned_id: null,
    assigned_name: null,
    sort_order: 0,
    source_event_service_id: null,
    created_at: "",
    updated_at: "",
    ...overrides,
  };
}

beforeEach(() => {
  vi.clearAllMocks();
});

describe("getEventServiceChecklistItems", () => {
  it("returns only rows generated by this EventService, filtering out the Event's manually-created and other assignments' items", async () => {
    vi.mocked(getChecklistByEventId).mockResolvedValue([
      checklistItem({ id: "item_1", source_event_service_id: "es_1" }),
      checklistItem({ id: "item_2", source_event_service_id: "es_2" }),
      checklistItem({ id: "item_3", source_event_service_id: null }),
    ] as never);

    const items = await getEventServiceChecklistItems("es_1", "event_1");
    expect(items.map((item) => item.id)).toEqual(["item_1"]);
  });

  it("fetches through the Event's full checklist, since ChecklistItem has no direct EventService-scoped query", async () => {
    vi.mocked(getChecklistByEventId).mockResolvedValue([]);
    await getEventServiceChecklistItems("es_1", "event_9");
    expect(getChecklistByEventId).toHaveBeenCalledWith("event_9");
  });

  it("returns an empty array when this EventService generated no checklist items", async () => {
    vi.mocked(getChecklistByEventId).mockResolvedValue([checklistItem({ source_event_service_id: "es_other" })] as never);
    expect(await getEventServiceChecklistItems("es_1", "event_1")).toEqual([]);
  });
});
