import type { WorkspaceMemberRole } from "@/core/enums/workspaceRole";
import { PERMISSIONS, type Permission } from "@/core/enums/permission";

/**
 * The canonical default role -> permission matrix — must be kept in sync
 * with the seeded `role_permissions` data
 * (`supabase/migrations/20260724101000_team_seed_data.sql`; see that
 * file's comment for the full rationale). This is the single source of
 * truth for mock mode, where there's no `role_permissions` table to query;
 * Supabase mode reads the live table instead of this constant.
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<WorkspaceMemberRole, readonly Permission[]> = {
  owner: PERMISSIONS,
  admin: PERMISSIONS,
  manager: [
    "workspace.view",
    "team.view",
    "leads.view",
    "leads.create",
    "leads.update",
    "leads.archive",
    "clients.view",
    "clients.create",
    "clients.update",
    "clients.archive",
    "events.view",
    "events.create",
    "events.update",
    "events.archive",
    "contracts.view",
    "contracts.create",
    "contracts.update",
    "contracts.lifecycle",
    "finance.view",
    "finance.create",
    "finance.update",
    "finance.amounts.view",
    "documents.view",
    "documents.create",
    "documents.update",
    "documents.archive",
    "clients.portal_view",
    "analytics.view",
    "communications.view",
    "communications.manage",
    "notifications.view",
    "notifications.manage",
    "notifications.templates",
    "notifications.preferences",
    "assets.view",
    "assets.manage",
    "workforce.view",
    "workforce.manage",
    "workforce.capabilities.view",
    "workforce.capabilities.manage",
    "workforce.sensitive_data.view",
    "scheduling.view",
    "scheduling.manage",
    "allocations.view",
    "allocations.manage",
    "operational_planning.view",
    "operational_planning.manage",
    "execution_packages.view",
    "execution_packages.manage",
    "dispatch.view",
    "dispatch.manage",
    "field_operations.view",
    "field_operations.manage",
    "route_optimization.view",
    "route_optimization.manage",
    "operations_center.view",
    "operations_center.manage",
    "operations_alerts.acknowledge",
    "operations_alerts.resolve",
    "operations_incidents.manage",
    "client_journeys.view",
    "client_journeys.manage",
    "client_journeys.assign",
    "client_journeys.transition",
    "client_information_requests.view",
    "client_information_requests.manage",
    "proposal_templates.view",
    "proposal_templates.manage",
    "proposal_builder.view",
    "proposal_builder.manage",
    "proposal_versions.view",
    "proposal_versions.manage",
    "proposal_pricing.manage",
    "proposal_packages.manage",
    "proposal_addons.manage",
    "contract_templates.view",
    "contract_templates.manage",
    "contract_builder.view",
    "contract_builder.manage",
    "contract_versions.view",
    "contract_versions.manage",
    "contract_clauses.manage",
    "contract_variables.manage",
    "invoice_templates.view",
    "invoice_templates.manage",
    "invoice_builder.view",
    "invoice_builder.manage",
    "invoice_versions.view",
    "invoice_versions.manage",
    "invoice_adjustments.manage",
    "invoice_billing.manage",
    "reports.view",
    "reports.manage",
    "reports.build",
    "reports.snapshots",
    "reports.financial",
    "reports.executive",
    "executive_decisions.manage",
    "objectives.manage",
  ],
  staff: [
    "workspace.view",
    "team.view",
    "leads.view",
    "clients.view",
    "events.view",
    "contracts.view",
    "finance.view",
    "documents.view",
    "clients.portal_view",
    "communications.view",
    "notifications.view",
    "notifications.preferences",
    "assets.view",
    "workforce.view",
    "workforce.capabilities.view",
    "scheduling.view",
    "allocations.view",
    "operational_planning.view",
    "execution_packages.view",
    "dispatch.view",
    "field_operations.view",
    "route_optimization.view",
    "operations_center.view",
    "client_journeys.view",
    "client_information_requests.view",
    "proposal_templates.view",
    "proposal_builder.view",
    "proposal_versions.view",
    "contract_templates.view",
    "contract_builder.view",
    "contract_versions.view",
    "invoice_templates.view",
    "invoice_builder.view",
    "invoice_versions.view",
    "reports.view",
  ],
};

export function getDefaultRolePermissions(role: WorkspaceMemberRole): Permission[] {
  return [...DEFAULT_ROLE_PERMISSIONS[role]];
}

export function roleHasPermission(role: WorkspaceMemberRole, permission: Permission): boolean {
  return (DEFAULT_ROLE_PERMISSIONS[role] as readonly string[]).includes(permission);
}
