"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getExecutiveInsightsData } from "@/modules/analytics/insights/getExecutiveInsightsData";
import { Card } from "@/components/ui/Card";
import { Badge, type BadgeTone } from "@/components/ui/Badge";
import { Skeleton } from "@/components/ui/Skeleton";
import { ErrorState } from "@/components/ui/ErrorState";
import type { ExecutiveInsight, ExecutiveInsightSeverity } from "@/types/businessIntelligence";

type LoadState = { status: "loading" } | { status: "error"; message: string } | { status: "ready"; insights: ExecutiveInsight[] };

const SEVERITY_TONE: Record<ExecutiveInsightSeverity, BadgeTone> = {
  info: "neutral",
  positive: "success",
  warning: "warning",
  critical: "danger",
};

const SEVERITY_RANK: Record<ExecutiveInsightSeverity, number> = { critical: 0, warning: 1, positive: 2, info: 3 };
const MAX_ITEMS = 3;

/**
 * Phase 08 — "Insights / Attention": every insight here is generated by the
 * same deterministic, rule-based `ExecutiveInsightsEngine` the Bloom AI
 * Insights tab already uses (Step 12) — no separate AI system, no invented
 * predictions. Restrained to the top 3 by severity so this reads as a
 * glance, not a second copy of the full Insights tab.
 */
export function AttentionInsightsSection() {
  const router = useRouter();
  const [state, setState] = useState<LoadState>({ status: "loading" });

  const fetchData = () =>
    getExecutiveInsightsData().then((result) => {
      if (result.success) setState({ status: "ready", insights: result.data });
      else setState({ status: "error", message: result.error });
    });

  useEffect(() => {
    fetchData();
  }, []);

  if (state.status === "loading") {
    return (
      <Card>
        <Skeleton className="h-24 w-full" />
      </Card>
    );
  }

  if (state.status === "error") {
    return (
      <Card>
        <ErrorState message={state.message} onRetry={fetchData} />
      </Card>
    );
  }

  const top = [...state.insights].sort((a, b) => SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity]).slice(0, MAX_ITEMS);

  return (
    <Card>
      <h3 className="font-serif text-[17px] font-semibold text-text">Needs Your Attention</h3>
      {top.length === 0 ? (
        <p className="mt-2 text-xs text-text-muted">Nothing needs your attention right now.</p>
      ) : (
        <div className="mt-3 space-y-3">
          {top.map((insight) => (
            <div key={insight.id} className="flex items-start justify-between gap-3 border-b border-border/60 pb-3 last:border-0 last:pb-0">
              <div>
                <div className="flex items-center gap-2">
                  <Badge tone={SEVERITY_TONE[insight.severity]}>{insight.severity}</Badge>
                  <p className="font-serif text-sm font-semibold text-text">{insight.title}</p>
                </div>
                <p className="mt-1 text-xs text-text-muted">{insight.detail}</p>
              </div>
              {insight.drillDown ? (
                <button type="button" className="shrink-0 text-xs text-accent hover:underline" onClick={() => router.push(insight.drillDown!.href)}>
                  {insight.drillDown.label} →
                </button>
              ) : null}
            </div>
          ))}
        </div>
      )}
    </Card>
  );
}
