import type { EntityType } from "@/core/enums/entityType";
import type { ChecklistCategory } from "@/core/enums/checklistCategory";
import type { ChecklistStatus } from "@/core/enums/checklistStatus";
import type { NotePriority } from "@/core/enums/notePriority";
import type { AssignedType } from "@/core/enums/assignedType";

/**
 * A reusable checklist item, not hardcoded to Events — same polymorphic
 * owner_type/owner_id shape as Note and TimelineActivity, reusing the same
 * EntityType union so a future owner (e.g. a Contract) can adopt it without
 * a new type. Only "event" is a real owner today.
 *
 * Same polymorphic-owner caveat as Notes/Timeline: owner_id can't carry a
 * normal foreign key, so every query MUST scope by workspace_id together
 * with owner_type/owner_id, never owner_id alone.
 *
 * priority reuses NotePriority (low/normal/high/critical) rather than a new
 * near-duplicate enum — the four-tier urgency scale means the same thing
 * here as it does on a Note. (Kept independent of EventPriority, which
 * gained a fifth "urgent" tier — Notes/Checklist priority is existing,
 * protected architecture and wasn't touched.)
 *
 * Assignment is generalized the same way ownership is: assigned_type/
 * assigned_id/assigned_name instead of a single assigned_to string, so a
 * checklist item can point at an Employee, Vendor, or Client once those
 * modules exist without another schema change. No Employee/Vendor module
 * exists yet, so assigned_id stays null in practice today — assigned_name
 * carries a free-text display name in the meantime.
 *
 * `source_event_service_id`/`template_snapshot` (Services Foundation phase,
 * Phase 2a) are set only for a row generated by an EventService assignment
 * — both null for a manually-created item. `template_snapshot` freezes
 * exactly what the pinned ServiceVersion's ServiceChecklistTemplateItem
 * produced at generation time; comparing it against this row's own live
 * fields is how the UI computes "is this overridden from its Service
 * template" without a separate stored boolean — the Event Override strategy
 * from docs/services.md. Neither field changes what this row IS: it remains
 * a completely ordinary ChecklistItem, read by every existing surface
 * (ChecklistSummaryCard, Event Health, the AI Operations Brief) unchanged.
 */
export interface ChecklistItemTemplateSnapshot {
  title: string;
  category: ChecklistCategory;
  priority: NotePriority;
  due_date: string | null;
}

export interface ChecklistItem {
  id: string;
  workspace_id: string;
  owner_type: EntityType;
  owner_id: string;
  title: string;
  description: string | null;
  category: ChecklistCategory;
  priority: NotePriority;
  status: ChecklistStatus;
  due_date: string | null;
  completed_at: string | null;
  assigned_type: AssignedType;
  assigned_id: string | null;
  assigned_name: string | null;
  sort_order: number;
  /** Optional — present only on rows generated by an EventService assignment; absent (not just null) on every pre-existing and every manually-created row, so no existing construction site needs updating. */
  source_event_service_id?: string | null;
  template_snapshot?: ChecklistItemTemplateSnapshot | null;
  /**
   * Checkpoint 14 — opt-in visibility into the Client Portal's own
   * read-only Checklist surface (Step 7). Optional, the same "absent on
   * every pre-existing row" convention `source_event_service_id` already
   * established, so it defaults to not-visible without a data migration.
   * A client may only ever read/complete/comment on a row where this is
   * `true` — internal-only checklist items (the vast majority) stay
   * invisible to the Client Portal exactly as before this checkpoint.
   */
  client_visible?: boolean;
  /** The client's own most recent comment on this item, via the Client Portal — optional, absent on every row a client has never commented on. Never written by internal staff. */
  client_comment?: string | null;
  created_at: string;
  updated_at: string;
}
