/**
 * HAND-AUTHORED PLACEHOLDER — not generated from a live database.
 *
 * Shaped to match the output of `npm run supabase:types` (`supabase gen
 * types typescript`) so it's a drop-in replacement once a real project is
 * linked and the migrations in `supabase/migrations/` have been applied.
 * Covers the Supabase Foundation tables (profiles, workspaces,
 * workspace_members), the Leads migration tables (leads, notes,
 * timeline_activities), the Clients migration table (clients), the
 * Events migration tables (events, checklist_items, event_schedule_items),
 * the Media Library table (media_assets), and the Contracts migration
 * tables (contract_templates, contracts, contract_exhibits) plus their RLS
 * helper functions and the convert_lead_to_client/
 * apply_default_event_checklist/generate_contract_number RPCs — regenerate
 * this file after every migration change; do not hand-edit table shapes
 * once live generation is available.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          email: string;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          email: string;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          email?: string;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      workspaces: {
        Row: {
          id: string;
          name: string;
          slug: string;
          created_by: string;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          created_by: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      workspace_members: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          role: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          role: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          role?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          workspace_id: string;
          first_name: string;
          last_name: string;
          email: string;
          phone: string | null;
          instagram: string | null;
          source: string;
          event_type: string | null;
          event_date: string | null;
          location: string | null;
          budget_min: number | null;
          budget_max: number | null;
          message: string | null;
          status: string;
          assigned_to: string | null;
          converted_client_id: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          first_name: string;
          last_name: string;
          email: string;
          phone?: string | null;
          instagram?: string | null;
          source: string;
          event_type?: string | null;
          event_date?: string | null;
          location?: string | null;
          budget_min?: number | null;
          budget_max?: number | null;
          message?: string | null;
          status?: string;
          assigned_to?: string | null;
          converted_client_id?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string | null;
          instagram?: string | null;
          source?: string;
          event_type?: string | null;
          event_date?: string | null;
          location?: string | null;
          budget_min?: number | null;
          budget_max?: number | null;
          message?: string | null;
          status?: string;
          assigned_to?: string | null;
          converted_client_id?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      notes: {
        Row: {
          id: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          title: string;
          content: string;
          category: string;
          priority: string;
          is_pinned: boolean;
          attachments: Json;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          title: string;
          content: string;
          category: string;
          priority: string;
          is_pinned?: boolean;
          attachments?: Json;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          owner_type?: string;
          owner_id?: string;
          title?: string;
          content?: string;
          category?: string;
          priority?: string;
          is_pinned?: boolean;
          attachments?: Json;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      timeline_activities: {
        Row: {
          id: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          type: string;
          description: string;
          actor: string;
          timestamp: string;
          metadata: Json | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          type: string;
          description: string;
          actor: string;
          timestamp?: string;
          metadata?: Json | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          owner_type?: string;
          owner_id?: string;
          type?: string;
          description?: string;
          actor?: string;
          timestamp?: string;
          metadata?: Json | null;
        };
        Relationships: [];
      };
      clients: {
        Row: {
          id: string;
          workspace_id: string;
          originating_lead_id: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone: string | null;
          instagram: string | null;
          preferred_contact_method: string | null;
          partner_name: string | null;
          relationship_status: string | null;
          important_dates: Json;
          address: string | null;
          city: string | null;
          state: string | null;
          zip_code: string | null;
          source: string | null;
          tags: string[];
          internal_status: string;
          is_returning: boolean;
          how_they_met: string | null;
          first_date: string | null;
          relationship_anniversary: string | null;
          engagement_date: string | null;
          wedding_date: string | null;
          favorite_colors: string | null;
          favorite_flowers: string | null;
          favorite_music: string | null;
          favorite_food: string | null;
          favorite_drinks: string | null;
          preferred_style: string | null;
          disliked_elements: string | null;
          allergies: string | null;
          accessibility_needs: string | null;
          dietary_restrictions: string | null;
          preferred_communication_time: string | null;
          do_not_call: boolean;
          surprise_event_confidentiality: boolean;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          is_vip: boolean;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          originating_lead_id?: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone?: string | null;
          instagram?: string | null;
          preferred_contact_method?: string | null;
          partner_name?: string | null;
          relationship_status?: string | null;
          important_dates?: Json;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          source?: string | null;
          tags?: string[];
          internal_status?: string;
          is_returning?: boolean;
          how_they_met?: string | null;
          first_date?: string | null;
          relationship_anniversary?: string | null;
          engagement_date?: string | null;
          wedding_date?: string | null;
          favorite_colors?: string | null;
          favorite_flowers?: string | null;
          favorite_music?: string | null;
          favorite_food?: string | null;
          favorite_drinks?: string | null;
          preferred_style?: string | null;
          disliked_elements?: string | null;
          allergies?: string | null;
          accessibility_needs?: string | null;
          dietary_restrictions?: string | null;
          preferred_communication_time?: string | null;
          do_not_call?: boolean;
          surprise_event_confidentiality?: boolean;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          is_vip?: boolean;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          originating_lead_id?: string | null;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string | null;
          instagram?: string | null;
          preferred_contact_method?: string | null;
          partner_name?: string | null;
          relationship_status?: string | null;
          important_dates?: Json;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          source?: string | null;
          tags?: string[];
          internal_status?: string;
          is_returning?: boolean;
          how_they_met?: string | null;
          first_date?: string | null;
          relationship_anniversary?: string | null;
          engagement_date?: string | null;
          wedding_date?: string | null;
          favorite_colors?: string | null;
          favorite_flowers?: string | null;
          favorite_music?: string | null;
          favorite_food?: string | null;
          favorite_drinks?: string | null;
          preferred_style?: string | null;
          disliked_elements?: string | null;
          allergies?: string | null;
          accessibility_needs?: string | null;
          dietary_restrictions?: string | null;
          preferred_communication_time?: string | null;
          do_not_call?: boolean;
          surprise_event_confidentiality?: boolean;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          is_vip?: boolean;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      events: {
        Row: {
          id: string;
          workspace_id: string;
          client_id: string;
          originating_lead_id: string | null;
          title: string;
          event_type: string;
          status: string;
          lifecycle_stage: string;
          event_date: string | null;
          start_time: string | null;
          end_time: string | null;
          timezone: string | null;
          location_name: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          zip_code: string | null;
          latitude: number | null;
          longitude: number | null;
          guest_count: number | null;
          budget_min: number | null;
          budget_max: number | null;
          package_name: string | null;
          theme: string | null;
          color_palette: string | null;
          surprise_event: boolean;
          confidentiality_notes: string | null;
          accessibility_notes: string | null;
          dietary_notes: string | null;
          weather_plan: string | null;
          backup_location: string | null;
          internal_summary: string | null;
          assigned_owner: string | null;
          priority: string;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          completed_at: string | null;
          cancelled_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          client_id: string;
          originating_lead_id?: string | null;
          title: string;
          event_type: string;
          status?: string;
          lifecycle_stage?: string;
          event_date?: string | null;
          start_time?: string | null;
          end_time?: string | null;
          timezone?: string | null;
          location_name?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          guest_count?: number | null;
          budget_min?: number | null;
          budget_max?: number | null;
          package_name?: string | null;
          theme?: string | null;
          color_palette?: string | null;
          surprise_event?: boolean;
          confidentiality_notes?: string | null;
          accessibility_notes?: string | null;
          dietary_notes?: string | null;
          weather_plan?: string | null;
          backup_location?: string | null;
          internal_summary?: string | null;
          assigned_owner?: string | null;
          priority?: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          client_id?: string;
          originating_lead_id?: string | null;
          title?: string;
          event_type?: string;
          status?: string;
          lifecycle_stage?: string;
          event_date?: string | null;
          start_time?: string | null;
          end_time?: string | null;
          timezone?: string | null;
          location_name?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          guest_count?: number | null;
          budget_min?: number | null;
          budget_max?: number | null;
          package_name?: string | null;
          theme?: string | null;
          color_palette?: string | null;
          surprise_event?: boolean;
          confidentiality_notes?: string | null;
          accessibility_notes?: string | null;
          dietary_notes?: string | null;
          weather_plan?: string | null;
          backup_location?: string | null;
          internal_summary?: string | null;
          assigned_owner?: string | null;
          priority?: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
        };
        Relationships: [];
      };
      checklist_items: {
        Row: {
          id: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          title: string;
          description: string | null;
          category: string;
          priority: string;
          status: string;
          due_date: string | null;
          completed_at: string | null;
          assigned_type: string;
          assigned_id: string | null;
          assigned_name: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          title: string;
          description?: string | null;
          category: string;
          priority: string;
          status?: string;
          due_date?: string | null;
          completed_at?: string | null;
          assigned_type?: string;
          assigned_id?: string | null;
          assigned_name?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          owner_type?: string;
          owner_id?: string;
          title?: string;
          description?: string | null;
          category?: string;
          priority?: string;
          status?: string;
          due_date?: string | null;
          completed_at?: string | null;
          assigned_type?: string;
          assigned_id?: string | null;
          assigned_name?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      event_schedule_items: {
        Row: {
          id: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          title: string;
          description: string | null;
          start_time: string | null;
          end_time: string | null;
          location: string | null;
          assigned_to: string | null;
          category: string;
          status: string;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          title: string;
          description?: string | null;
          start_time?: string | null;
          end_time?: string | null;
          location?: string | null;
          assigned_to?: string | null;
          category: string;
          status?: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          owner_type?: string;
          owner_id?: string;
          title?: string;
          description?: string | null;
          start_time?: string | null;
          end_time?: string | null;
          location?: string | null;
          assigned_to?: string | null;
          category?: string;
          status?: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      contract_templates: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          description: string | null;
          category: string;
          body: string;
          version: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          description?: string | null;
          category: string;
          body: string;
          version?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          description?: string | null;
          category?: string;
          body?: string;
          version?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      contracts: {
        Row: {
          id: string;
          workspace_id: string;
          client_id: string;
          event_id: string | null;
          template_id: string | null;
          contract_number: string;
          title: string;
          description: string | null;
          status: string;
          signature_status: string;
          version: number;
          version_history: Json;
          effective_date: string | null;
          expiration_date: string | null;
          signed_at: string | null;
          sent_at: string | null;
          viewed_at: string | null;
          declined_at: string | null;
          cancelled_at: string | null;
          archived_at: string | null;
          total_value: number | null;
          deposit_required: boolean;
          deposit_amount: number | null;
          remaining_balance: number | null;
          currency: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          client_id: string;
          event_id?: string | null;
          template_id?: string | null;
          contract_number: string;
          title: string;
          description?: string | null;
          status?: string;
          signature_status?: string;
          version?: number;
          version_history?: Json;
          effective_date?: string | null;
          expiration_date?: string | null;
          signed_at?: string | null;
          sent_at?: string | null;
          viewed_at?: string | null;
          declined_at?: string | null;
          cancelled_at?: string | null;
          archived_at?: string | null;
          total_value?: number | null;
          deposit_required?: boolean;
          deposit_amount?: number | null;
          remaining_balance?: number | null;
          currency?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          client_id?: string;
          event_id?: string | null;
          template_id?: string | null;
          contract_number?: string;
          title?: string;
          description?: string | null;
          status?: string;
          signature_status?: string;
          version?: number;
          version_history?: Json;
          effective_date?: string | null;
          expiration_date?: string | null;
          signed_at?: string | null;
          sent_at?: string | null;
          viewed_at?: string | null;
          declined_at?: string | null;
          cancelled_at?: string | null;
          archived_at?: string | null;
          total_value?: number | null;
          deposit_required?: boolean;
          deposit_amount?: number | null;
          remaining_balance?: number | null;
          currency?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      contract_exhibits: {
        Row: {
          id: string;
          workspace_id: string;
          contract_id: string;
          title: string;
          description: string | null;
          display_order: number;
          document_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          contract_id: string;
          title: string;
          description?: string | null;
          display_order?: number;
          document_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          contract_id?: string;
          title?: string;
          description?: string | null;
          display_order?: number;
          document_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      media_assets: {
        Row: {
          id: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          original_filename: string;
          stored_filename: string;
          storage_bucket: string;
          storage_path: string;
          mime_type: string;
          extension: string;
          file_size: number;
          checksum: string;
          width: number | null;
          height: number | null;
          duration: number | null;
          version: number;
          uploaded_by: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          original_filename: string;
          stored_filename: string;
          storage_bucket: string;
          storage_path: string;
          mime_type: string;
          extension: string;
          file_size: number;
          checksum: string;
          width?: number | null;
          height?: number | null;
          duration?: number | null;
          version?: number;
          uploaded_by?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          owner_type?: string;
          owner_id?: string;
          original_filename?: string;
          stored_filename?: string;
          storage_bucket?: string;
          storage_path?: string;
          mime_type?: string;
          extension?: string;
          file_size?: number;
          checksum?: string;
          width?: number | null;
          height?: number | null;
          duration?: number | null;
          version?: number;
          uploaded_by?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      invoices: {
        Row: {
          id: string;
          workspace_id: string;
          client_id: string;
          event_id: string | null;
          contract_id: string | null;
          invoice_number: string;
          title: string;
          description: string | null;
          status: string;
          issue_date: string | null;
          due_date: string | null;
          subtotal_minor: number;
          tax_minor: number;
          discount_minor: number;
          total_minor: number;
          paid_minor: number;
          balance_minor: number;
          currency: string;
          notes: string | null;
          sent_at: string | null;
          viewed_at: string | null;
          paid_at: string | null;
          overdue_at: string | null;
          voided_at: string | null;
          archived_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          client_id: string;
          event_id?: string | null;
          contract_id?: string | null;
          invoice_number: string;
          title: string;
          description?: string | null;
          status?: string;
          issue_date?: string | null;
          due_date?: string | null;
          subtotal_minor: number;
          tax_minor?: number;
          discount_minor?: number;
          total_minor: number;
          paid_minor?: number;
          balance_minor: number;
          currency?: string;
          notes?: string | null;
          sent_at?: string | null;
          viewed_at?: string | null;
          paid_at?: string | null;
          overdue_at?: string | null;
          voided_at?: string | null;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          client_id?: string;
          event_id?: string | null;
          contract_id?: string | null;
          invoice_number?: string;
          title?: string;
          description?: string | null;
          status?: string;
          issue_date?: string | null;
          due_date?: string | null;
          subtotal_minor?: number;
          tax_minor?: number;
          discount_minor?: number;
          total_minor?: number;
          paid_minor?: number;
          balance_minor?: number;
          currency?: string;
          notes?: string | null;
          sent_at?: string | null;
          viewed_at?: string | null;
          paid_at?: string | null;
          overdue_at?: string | null;
          voided_at?: string | null;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          workspace_id: string;
          invoice_id: string | null;
          client_id: string;
          event_id: string | null;
          contract_id: string | null;
          payment_type: string;
          status: string;
          amount_minor: number;
          currency: string;
          payment_method: string;
          reference: string | null;
          transaction_date: string;
          received_at: string | null;
          failed_at: string | null;
          refunded_at: string | null;
          notes: string | null;
          document_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          invoice_id?: string | null;
          client_id: string;
          event_id?: string | null;
          contract_id?: string | null;
          payment_type?: string;
          status?: string;
          amount_minor: number;
          currency?: string;
          payment_method: string;
          reference?: string | null;
          transaction_date: string;
          received_at?: string | null;
          failed_at?: string | null;
          refunded_at?: string | null;
          notes?: string | null;
          document_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          invoice_id?: string | null;
          client_id?: string;
          event_id?: string | null;
          contract_id?: string | null;
          payment_type?: string;
          status?: string;
          amount_minor?: number;
          currency?: string;
          payment_method?: string;
          reference?: string | null;
          transaction_date?: string;
          received_at?: string | null;
          failed_at?: string | null;
          refunded_at?: string | null;
          notes?: string | null;
          document_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      expenses: {
        Row: {
          id: string;
          workspace_id: string;
          event_id: string | null;
          client_id: string | null;
          contract_id: string | null;
          supplier_id: string | null;
          team_member_id: string | null;
          category: string;
          status: string;
          description: string;
          amount_minor: number;
          currency: string;
          transaction_date: string;
          due_date: string | null;
          paid_at: string | null;
          reimbursable: boolean;
          reimbursed_at: string | null;
          reference: string | null;
          notes: string | null;
          document_id: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          event_id?: string | null;
          client_id?: string | null;
          contract_id?: string | null;
          supplier_id?: string | null;
          team_member_id?: string | null;
          category?: string;
          status?: string;
          description: string;
          amount_minor: number;
          currency?: string;
          transaction_date: string;
          due_date?: string | null;
          paid_at?: string | null;
          reimbursable?: boolean;
          reimbursed_at?: string | null;
          reference?: string | null;
          notes?: string | null;
          document_id?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          event_id?: string | null;
          client_id?: string | null;
          contract_id?: string | null;
          supplier_id?: string | null;
          team_member_id?: string | null;
          category?: string;
          status?: string;
          description?: string;
          amount_minor?: number;
          currency?: string;
          transaction_date?: string;
          due_date?: string | null;
          paid_at?: string | null;
          reimbursable?: boolean;
          reimbursed_at?: string | null;
          reference?: string | null;
          notes?: string | null;
          document_id?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_workspace_member: {
        Args: { workspace_uuid: string };
        Returns: boolean;
      };
      has_workspace_role: {
        Args: { workspace_uuid: string; allowed_roles: string[] };
        Returns: boolean;
      };
      current_user_workspace_ids: {
        Args: Record<string, never>;
        Returns: string[];
      };
      convert_lead_to_client: {
        Args: { p_lead_id: string; p_actor: string };
        Returns: Json;
      };
      apply_default_event_checklist: {
        Args: { p_event_id: string; p_items: Json; p_description: string; p_actor: string };
        Returns: Json;
      };
      generate_contract_number: {
        Args: { p_workspace_id: string };
        Returns: string;
      };
      generate_invoice_number: {
        Args: { p_workspace_id: string };
        Returns: string;
      };
      recompute_invoice_balance: {
        Args: { p_invoice_id: string; p_actor: string };
        Returns: Database["public"]["Tables"]["invoices"]["Row"];
      };
      process_payment_refund: {
        Args: { p_original_payment_id: string; p_amount_minor: number; p_actor: string };
        Returns: Database["public"]["Tables"]["payments"]["Row"];
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
