/**
 * HAND-AUTHORED PLACEHOLDER — not generated from a live database.
 *
 * Shaped to match the output of `npm run supabase:types` (`supabase gen
 * types typescript`) so it's a drop-in replacement once a real project is
 * linked and the migrations in `supabase/migrations/` have been applied.
 * Covers every table and RPC function from every applied migration
 * (Supabase Foundation through the Team foundation: roles, permissions,
 * role_permissions, workspace_invitations) — regenerate this file after
 * every migration change; do not hand-edit table shapes once live
 * generation is available.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          email: string;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          email: string;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          email?: string;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      workspaces: {
        Row: {
          id: string;
          name: string;
          slug: string;
          created_by: string;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          created_by: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      workspace_members: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          role: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          role: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          role?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      roles: {
        Row: {
          id: string;
          name: string;
          description: string;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          description: string;
          sort_order: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      permissions: {
        Row: {
          id: string;
          description: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          description: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          description?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      role_permissions: {
        Row: {
          role_id: string;
          permission_id: string;
          created_at: string;
        };
        Insert: {
          role_id: string;
          permission_id: string;
          created_at?: string;
        };
        Update: {
          role_id?: string;
          permission_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      workspace_invitations: {
        Row: {
          id: string;
          workspace_id: string;
          email: string;
          invited_role: string;
          invited_by: string;
          token_hash: string;
          status: string;
          expires_at: string;
          accepted_at: string | null;
          accepted_by: string | null;
          revoked_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          email: string;
          invited_role: string;
          invited_by: string;
          token_hash: string;
          status?: string;
          expires_at: string;
          accepted_at?: string | null;
          accepted_by?: string | null;
          revoked_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          email?: string;
          invited_role?: string;
          invited_by?: string;
          token_hash?: string;
          status?: string;
          expires_at?: string;
          accepted_at?: string | null;
          accepted_by?: string | null;
          revoked_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      client_accounts: {
        Row: {
          id: string;
          workspace_id: string;
          client_id: string;
          auth_user_id: string;
          email: string;
          status: string;
          invited_by: string;
          accepted_at: string | null;
          suspended_at: string | null;
          revoked_at: string | null;
          last_access_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          client_id: string;
          auth_user_id: string;
          email: string;
          status?: string;
          invited_by: string;
          accepted_at?: string | null;
          suspended_at?: string | null;
          revoked_at?: string | null;
          last_access_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          client_id?: string;
          auth_user_id?: string;
          email?: string;
          status?: string;
          invited_by?: string;
          accepted_at?: string | null;
          suspended_at?: string | null;
          revoked_at?: string | null;
          last_access_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      client_invitations: {
        Row: {
          id: string;
          workspace_id: string;
          client_id: string;
          email: string;
          invited_by: string;
          token_hash: string;
          status: string;
          expires_at: string;
          accepted_at: string | null;
          revoked_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          client_id: string;
          email: string;
          invited_by: string;
          token_hash: string;
          status?: string;
          expires_at: string;
          accepted_at?: string | null;
          revoked_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          client_id?: string;
          email?: string;
          invited_by?: string;
          token_hash?: string;
          status?: string;
          expires_at?: string;
          accepted_at?: string | null;
          revoked_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          workspace_id: string;
          first_name: string;
          last_name: string;
          email: string;
          phone: string | null;
          instagram: string | null;
          source: string;
          event_type: string | null;
          event_date: string | null;
          location: string | null;
          budget_min: number | null;
          budget_max: number | null;
          message: string | null;
          status: string;
          assigned_to: string | null;
          converted_client_id: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          first_name: string;
          last_name: string;
          email: string;
          phone?: string | null;
          instagram?: string | null;
          source: string;
          event_type?: string | null;
          event_date?: string | null;
          location?: string | null;
          budget_min?: number | null;
          budget_max?: number | null;
          message?: string | null;
          status?: string;
          assigned_to?: string | null;
          converted_client_id?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string | null;
          instagram?: string | null;
          source?: string;
          event_type?: string | null;
          event_date?: string | null;
          location?: string | null;
          budget_min?: number | null;
          budget_max?: number | null;
          message?: string | null;
          status?: string;
          assigned_to?: string | null;
          converted_client_id?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      notes: {
        Row: {
          id: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          title: string;
          content: string;
          category: string;
          priority: string;
          is_pinned: boolean;
          attachments: Json;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          title: string;
          content: string;
          category: string;
          priority: string;
          is_pinned?: boolean;
          attachments?: Json;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          owner_type?: string;
          owner_id?: string;
          title?: string;
          content?: string;
          category?: string;
          priority?: string;
          is_pinned?: boolean;
          attachments?: Json;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      timeline_activities: {
        Row: {
          id: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          type: string;
          description: string;
          actor: string;
          timestamp: string;
          metadata: Json | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          type: string;
          description: string;
          actor: string;
          timestamp?: string;
          metadata?: Json | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          owner_type?: string;
          owner_id?: string;
          type?: string;
          description?: string;
          actor?: string;
          timestamp?: string;
          metadata?: Json | null;
        };
        Relationships: [];
      };
      clients: {
        Row: {
          id: string;
          workspace_id: string;
          originating_lead_id: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone: string | null;
          instagram: string | null;
          preferred_contact_method: string | null;
          partner_name: string | null;
          relationship_status: string | null;
          important_dates: Json;
          address: string | null;
          city: string | null;
          state: string | null;
          zip_code: string | null;
          source: string | null;
          tags: string[];
          internal_status: string;
          is_returning: boolean;
          how_they_met: string | null;
          first_date: string | null;
          relationship_anniversary: string | null;
          engagement_date: string | null;
          wedding_date: string | null;
          favorite_colors: string | null;
          favorite_flowers: string | null;
          favorite_music: string | null;
          favorite_food: string | null;
          favorite_drinks: string | null;
          favorite_restaurants: string | null;
          preferred_style: string | null;
          disliked_elements: string | null;
          allergies: string | null;
          accessibility_needs: string | null;
          dietary_restrictions: string | null;
          preferred_communication_time: string | null;
          do_not_call: boolean;
          surprise_event_confidentiality: boolean;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          is_vip: boolean;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          pending_recovery: Json | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          originating_lead_id?: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone?: string | null;
          instagram?: string | null;
          preferred_contact_method?: string | null;
          partner_name?: string | null;
          relationship_status?: string | null;
          important_dates?: Json;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          source?: string | null;
          tags?: string[];
          internal_status?: string;
          is_returning?: boolean;
          how_they_met?: string | null;
          first_date?: string | null;
          relationship_anniversary?: string | null;
          engagement_date?: string | null;
          wedding_date?: string | null;
          favorite_colors?: string | null;
          favorite_flowers?: string | null;
          favorite_music?: string | null;
          favorite_food?: string | null;
          favorite_drinks?: string | null;
          favorite_restaurants?: string | null;
          preferred_style?: string | null;
          disliked_elements?: string | null;
          allergies?: string | null;
          accessibility_needs?: string | null;
          dietary_restrictions?: string | null;
          preferred_communication_time?: string | null;
          do_not_call?: boolean;
          surprise_event_confidentiality?: boolean;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          is_vip?: boolean;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          pending_recovery?: Json | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          originating_lead_id?: string | null;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string | null;
          instagram?: string | null;
          preferred_contact_method?: string | null;
          partner_name?: string | null;
          relationship_status?: string | null;
          important_dates?: Json;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          source?: string | null;
          tags?: string[];
          internal_status?: string;
          is_returning?: boolean;
          how_they_met?: string | null;
          first_date?: string | null;
          relationship_anniversary?: string | null;
          engagement_date?: string | null;
          wedding_date?: string | null;
          favorite_colors?: string | null;
          favorite_flowers?: string | null;
          favorite_music?: string | null;
          favorite_food?: string | null;
          favorite_drinks?: string | null;
          favorite_restaurants?: string | null;
          preferred_style?: string | null;
          disliked_elements?: string | null;
          allergies?: string | null;
          accessibility_needs?: string | null;
          dietary_restrictions?: string | null;
          preferred_communication_time?: string | null;
          do_not_call?: boolean;
          surprise_event_confidentiality?: boolean;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          is_vip?: boolean;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          pending_recovery?: Json | null;
        };
        Relationships: [];
      };
      events: {
        Row: {
          id: string;
          workspace_id: string;
          client_id: string;
          originating_lead_id: string | null;
          title: string;
          event_type: string;
          status: string;
          lifecycle_stage: string;
          event_date: string | null;
          start_time: string | null;
          end_time: string | null;
          timezone: string | null;
          location_name: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          zip_code: string | null;
          latitude: number | null;
          longitude: number | null;
          guest_count: number | null;
          budget_min: number | null;
          budget_max: number | null;
          package_name: string | null;
          theme: string | null;
          color_palette: string | null;
          surprise_event: boolean;
          confidentiality_notes: string | null;
          accessibility_notes: string | null;
          dietary_notes: string | null;
          weather_plan: string | null;
          backup_location: string | null;
          internal_summary: string | null;
          assigned_owner: string | null;
          priority: string;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          completed_at: string | null;
          cancelled_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          client_id: string;
          originating_lead_id?: string | null;
          title: string;
          event_type: string;
          status?: string;
          lifecycle_stage?: string;
          event_date?: string | null;
          start_time?: string | null;
          end_time?: string | null;
          timezone?: string | null;
          location_name?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          guest_count?: number | null;
          budget_min?: number | null;
          budget_max?: number | null;
          package_name?: string | null;
          theme?: string | null;
          color_palette?: string | null;
          surprise_event?: boolean;
          confidentiality_notes?: string | null;
          accessibility_notes?: string | null;
          dietary_notes?: string | null;
          weather_plan?: string | null;
          backup_location?: string | null;
          internal_summary?: string | null;
          assigned_owner?: string | null;
          priority?: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          client_id?: string;
          originating_lead_id?: string | null;
          title?: string;
          event_type?: string;
          status?: string;
          lifecycle_stage?: string;
          event_date?: string | null;
          start_time?: string | null;
          end_time?: string | null;
          timezone?: string | null;
          location_name?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          guest_count?: number | null;
          budget_min?: number | null;
          budget_max?: number | null;
          package_name?: string | null;
          theme?: string | null;
          color_palette?: string | null;
          surprise_event?: boolean;
          confidentiality_notes?: string | null;
          accessibility_notes?: string | null;
          dietary_notes?: string | null;
          weather_plan?: string | null;
          backup_location?: string | null;
          internal_summary?: string | null;
          assigned_owner?: string | null;
          priority?: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
        };
        Relationships: [];
      };
      checklist_items: {
        Row: {
          id: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          title: string;
          description: string | null;
          category: string;
          priority: string;
          status: string;
          due_date: string | null;
          completed_at: string | null;
          assigned_type: string;
          assigned_id: string | null;
          assigned_name: string | null;
          sort_order: number;
          source_event_service_id: string | null;
          template_snapshot: Json | null;
          client_visible: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          title: string;
          description?: string | null;
          category: string;
          priority: string;
          status?: string;
          due_date?: string | null;
          completed_at?: string | null;
          assigned_type?: string;
          assigned_id?: string | null;
          assigned_name?: string | null;
          sort_order?: number;
          source_event_service_id?: string | null;
          template_snapshot?: Json | null;
          client_visible?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          owner_type?: string;
          owner_id?: string;
          title?: string;
          description?: string | null;
          category?: string;
          priority?: string;
          status?: string;
          due_date?: string | null;
          completed_at?: string | null;
          assigned_type?: string;
          assigned_id?: string | null;
          assigned_name?: string | null;
          sort_order?: number;
          source_event_service_id?: string | null;
          template_snapshot?: Json | null;
          client_visible?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      event_schedule_items: {
        Row: {
          id: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          title: string;
          description: string | null;
          start_time: string | null;
          end_time: string | null;
          location: string | null;
          assigned_to: string | null;
          category: string;
          status: string;
          sort_order: number;
          source_event_service_id: string | null;
          template_snapshot: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          title: string;
          description?: string | null;
          start_time?: string | null;
          end_time?: string | null;
          location?: string | null;
          assigned_to?: string | null;
          category: string;
          status?: string;
          sort_order?: number;
          source_event_service_id?: string | null;
          template_snapshot?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          owner_type?: string;
          owner_id?: string;
          title?: string;
          description?: string | null;
          start_time?: string | null;
          end_time?: string | null;
          location?: string | null;
          assigned_to?: string | null;
          category?: string;
          status?: string;
          sort_order?: number;
          source_event_service_id?: string | null;
          template_snapshot?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      contract_templates: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          description: string | null;
          category: string;
          body: string;
          version: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          description?: string | null;
          category: string;
          body: string;
          version?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          description?: string | null;
          category?: string;
          body?: string;
          version?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      contracts: {
        Row: {
          id: string;
          workspace_id: string;
          client_id: string;
          event_id: string | null;
          template_id: string | null;
          contract_number: string;
          title: string;
          description: string | null;
          status: string;
          signature_status: string;
          version: number;
          version_history: Json;
          effective_date: string | null;
          expiration_date: string | null;
          signed_at: string | null;
          sent_at: string | null;
          viewed_at: string | null;
          declined_at: string | null;
          cancelled_at: string | null;
          archived_at: string | null;
          total_value: number | null;
          deposit_required: boolean;
          deposit_amount: number | null;
          remaining_balance: number | null;
          currency: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          client_id: string;
          event_id?: string | null;
          template_id?: string | null;
          contract_number: string;
          title: string;
          description?: string | null;
          status?: string;
          signature_status?: string;
          version?: number;
          version_history?: Json;
          effective_date?: string | null;
          expiration_date?: string | null;
          signed_at?: string | null;
          sent_at?: string | null;
          viewed_at?: string | null;
          declined_at?: string | null;
          cancelled_at?: string | null;
          archived_at?: string | null;
          total_value?: number | null;
          deposit_required?: boolean;
          deposit_amount?: number | null;
          remaining_balance?: number | null;
          currency?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          client_id?: string;
          event_id?: string | null;
          template_id?: string | null;
          contract_number?: string;
          title?: string;
          description?: string | null;
          status?: string;
          signature_status?: string;
          version?: number;
          version_history?: Json;
          effective_date?: string | null;
          expiration_date?: string | null;
          signed_at?: string | null;
          sent_at?: string | null;
          viewed_at?: string | null;
          declined_at?: string | null;
          cancelled_at?: string | null;
          archived_at?: string | null;
          total_value?: number | null;
          deposit_required?: boolean;
          deposit_amount?: number | null;
          remaining_balance?: number | null;
          currency?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      contract_exhibits: {
        Row: {
          id: string;
          workspace_id: string;
          contract_id: string;
          title: string;
          description: string | null;
          display_order: number;
          document_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          contract_id: string;
          title: string;
          description?: string | null;
          display_order?: number;
          document_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          contract_id?: string;
          title?: string;
          description?: string | null;
          display_order?: number;
          document_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      media_assets: {
        Row: {
          id: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          original_filename: string;
          stored_filename: string;
          storage_bucket: string;
          storage_path: string;
          mime_type: string;
          extension: string;
          file_size: number;
          checksum: string;
          width: number | null;
          height: number | null;
          duration: number | null;
          version: number;
          uploaded_by: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          original_filename: string;
          stored_filename: string;
          storage_bucket: string;
          storage_path: string;
          mime_type: string;
          extension: string;
          file_size: number;
          checksum: string;
          width?: number | null;
          height?: number | null;
          duration?: number | null;
          version?: number;
          uploaded_by?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          owner_type?: string;
          owner_id?: string;
          original_filename?: string;
          stored_filename?: string;
          storage_bucket?: string;
          storage_path?: string;
          mime_type?: string;
          extension?: string;
          file_size?: number;
          checksum?: string;
          width?: number | null;
          height?: number | null;
          duration?: number | null;
          version?: number;
          uploaded_by?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      invoices: {
        Row: {
          id: string;
          workspace_id: string;
          client_id: string;
          event_id: string | null;
          contract_id: string | null;
          invoice_number: string;
          title: string;
          description: string | null;
          status: string;
          issue_date: string | null;
          due_date: string | null;
          subtotal_minor: number;
          tax_minor: number;
          discount_minor: number;
          total_minor: number;
          paid_minor: number;
          balance_minor: number;
          currency: string;
          notes: string | null;
          sent_at: string | null;
          viewed_at: string | null;
          paid_at: string | null;
          overdue_at: string | null;
          voided_at: string | null;
          archived_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          client_id: string;
          event_id?: string | null;
          contract_id?: string | null;
          invoice_number: string;
          title: string;
          description?: string | null;
          status?: string;
          issue_date?: string | null;
          due_date?: string | null;
          subtotal_minor: number;
          tax_minor?: number;
          discount_minor?: number;
          total_minor: number;
          paid_minor?: number;
          balance_minor: number;
          currency?: string;
          notes?: string | null;
          sent_at?: string | null;
          viewed_at?: string | null;
          paid_at?: string | null;
          overdue_at?: string | null;
          voided_at?: string | null;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          client_id?: string;
          event_id?: string | null;
          contract_id?: string | null;
          invoice_number?: string;
          title?: string;
          description?: string | null;
          status?: string;
          issue_date?: string | null;
          due_date?: string | null;
          subtotal_minor?: number;
          tax_minor?: number;
          discount_minor?: number;
          total_minor?: number;
          paid_minor?: number;
          balance_minor?: number;
          currency?: string;
          notes?: string | null;
          sent_at?: string | null;
          viewed_at?: string | null;
          paid_at?: string | null;
          overdue_at?: string | null;
          voided_at?: string | null;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          workspace_id: string;
          invoice_id: string | null;
          client_id: string;
          event_id: string | null;
          contract_id: string | null;
          payment_type: string;
          status: string;
          amount_minor: number;
          currency: string;
          payment_method: string;
          reference: string | null;
          transaction_date: string;
          received_at: string | null;
          failed_at: string | null;
          refunded_at: string | null;
          notes: string | null;
          document_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          invoice_id?: string | null;
          client_id: string;
          event_id?: string | null;
          contract_id?: string | null;
          payment_type?: string;
          status?: string;
          amount_minor: number;
          currency?: string;
          payment_method: string;
          reference?: string | null;
          transaction_date: string;
          received_at?: string | null;
          failed_at?: string | null;
          refunded_at?: string | null;
          notes?: string | null;
          document_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          invoice_id?: string | null;
          client_id?: string;
          event_id?: string | null;
          contract_id?: string | null;
          payment_type?: string;
          status?: string;
          amount_minor?: number;
          currency?: string;
          payment_method?: string;
          reference?: string | null;
          transaction_date?: string;
          received_at?: string | null;
          failed_at?: string | null;
          refunded_at?: string | null;
          notes?: string | null;
          document_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      expenses: {
        Row: {
          id: string;
          workspace_id: string;
          event_id: string | null;
          client_id: string | null;
          contract_id: string | null;
          supplier_id: string | null;
          team_member_id: string | null;
          category: string;
          status: string;
          description: string;
          amount_minor: number;
          currency: string;
          transaction_date: string;
          due_date: string | null;
          paid_at: string | null;
          reimbursable: boolean;
          reimbursed_at: string | null;
          reference: string | null;
          notes: string | null;
          document_id: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          event_id?: string | null;
          client_id?: string | null;
          contract_id?: string | null;
          supplier_id?: string | null;
          team_member_id?: string | null;
          category?: string;
          status?: string;
          description: string;
          amount_minor: number;
          currency?: string;
          transaction_date: string;
          due_date?: string | null;
          paid_at?: string | null;
          reimbursable?: boolean;
          reimbursed_at?: string | null;
          reference?: string | null;
          notes?: string | null;
          document_id?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          event_id?: string | null;
          client_id?: string | null;
          contract_id?: string | null;
          supplier_id?: string | null;
          team_member_id?: string | null;
          category?: string;
          status?: string;
          description?: string;
          amount_minor?: number;
          currency?: string;
          transaction_date?: string;
          due_date?: string | null;
          paid_at?: string | null;
          reimbursable?: boolean;
          reimbursed_at?: string | null;
          reference?: string | null;
          notes?: string | null;
          document_id?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      documents: {
        Row: {
          id: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          folder_id: string | null;
          title: string;
          description: string | null;
          category: string;
          status: string;
          visibility: string;
          media_asset_id: string | null;
          version: number;
          is_latest_version: boolean;
          parent_document_id: string | null;
          contract_exhibit_id: string | null;
          event_id: string | null;
          client_id: string | null;
          contract_id: string | null;
          invoice_id: string | null;
          payment_id: string | null;
          expense_id: string | null;
          uploaded_by: string | null;
          uploaded_at: string;
          expires_at: string | null;
          archived_at: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          folder_id?: string | null;
          title: string;
          description?: string | null;
          category?: string;
          status?: string;
          visibility?: string;
          media_asset_id?: string | null;
          version?: number;
          is_latest_version?: boolean;
          parent_document_id?: string | null;
          contract_exhibit_id?: string | null;
          event_id?: string | null;
          client_id?: string | null;
          contract_id?: string | null;
          invoice_id?: string | null;
          payment_id?: string | null;
          expense_id?: string | null;
          uploaded_by?: string | null;
          uploaded_at?: string;
          expires_at?: string | null;
          archived_at?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          owner_type?: string;
          owner_id?: string;
          folder_id?: string | null;
          title?: string;
          description?: string | null;
          category?: string;
          status?: string;
          visibility?: string;
          media_asset_id?: string | null;
          version?: number;
          is_latest_version?: boolean;
          parent_document_id?: string | null;
          contract_exhibit_id?: string | null;
          event_id?: string | null;
          client_id?: string | null;
          contract_id?: string | null;
          invoice_id?: string | null;
          payment_id?: string | null;
          expense_id?: string | null;
          uploaded_by?: string | null;
          uploaded_at?: string;
          expires_at?: string | null;
          archived_at?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      document_folders: {
        Row: {
          id: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          parent_folder_id: string | null;
          name: string;
          description: string | null;
          sort_order: number;
          visibility: string;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          owner_type: string;
          owner_id: string;
          parent_folder_id?: string | null;
          name: string;
          description?: string | null;
          sort_order?: number;
          visibility?: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          owner_type?: string;
          owner_id?: string;
          parent_folder_id?: string | null;
          name?: string;
          description?: string | null;
          sort_order?: number;
          visibility?: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      vendors: {
        Row: {
          id: string;
          workspace_id: string;
          company_name: string;
          display_name: string | null;
          contact_person: string | null;
          email: string | null;
          phone: string | null;
          website: string | null;
          tax_id: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          zip_code: string | null;
          country: string | null;
          notes: string | null;
          status: string;
          tags: string[];
          default_currency: string;
          payment_terms: string | null;
          is_preferred: boolean;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          company_name: string;
          display_name?: string | null;
          contact_person?: string | null;
          email?: string | null;
          phone?: string | null;
          website?: string | null;
          tax_id?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          country?: string | null;
          notes?: string | null;
          status?: string;
          tags?: string[];
          default_currency?: string;
          payment_terms?: string | null;
          is_preferred?: boolean;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          company_name?: string;
          display_name?: string | null;
          contact_person?: string | null;
          email?: string | null;
          phone?: string | null;
          website?: string | null;
          tax_id?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          country?: string | null;
          notes?: string | null;
          status?: string;
          tags?: string[];
          default_currency?: string;
          payment_terms?: string | null;
          is_preferred?: boolean;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      inventory_items: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          description: string | null;
          sku: string | null;
          category: string | null;
          subcategory: string | null;
          item_type: string;
          tags: string[];
          status: string;
          condition: string | null;
          unit_of_measure: string | null;
          quantity_on_hand: number;
          quantity_available: number;
          quantity_reserved: number;
          reorder_level: number | null;
          target_stock_level: number | null;
          unit_cost: number | null;
          replacement_cost: number | null;
          rental_value: number | null;
          storage_location: string | null;
          bin_location: string | null;
          primary_vendor_id: string | null;
          purchase_date: string | null;
          last_inventory_check_at: string | null;
          notes: string | null;
          image_url: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          description?: string | null;
          sku?: string | null;
          category?: string | null;
          subcategory?: string | null;
          item_type: string;
          tags?: string[];
          status?: string;
          condition?: string | null;
          unit_of_measure?: string | null;
          quantity_on_hand?: number;
          quantity_available?: number;
          quantity_reserved?: number;
          reorder_level?: number | null;
          target_stock_level?: number | null;
          unit_cost?: number | null;
          replacement_cost?: number | null;
          rental_value?: number | null;
          storage_location?: string | null;
          bin_location?: string | null;
          primary_vendor_id?: string | null;
          purchase_date?: string | null;
          last_inventory_check_at?: string | null;
          notes?: string | null;
          image_url?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          description?: string | null;
          sku?: string | null;
          category?: string | null;
          subcategory?: string | null;
          item_type?: string;
          tags?: string[];
          status?: string;
          condition?: string | null;
          unit_of_measure?: string | null;
          quantity_on_hand?: number;
          quantity_available?: number;
          quantity_reserved?: number;
          reorder_level?: number | null;
          target_stock_level?: number | null;
          unit_cost?: number | null;
          replacement_cost?: number | null;
          rental_value?: number | null;
          storage_location?: string | null;
          bin_location?: string | null;
          primary_vendor_id?: string | null;
          purchase_date?: string | null;
          last_inventory_check_at?: string | null;
          notes?: string | null;
          image_url?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      inventory_movements: {
        Row: {
          id: string;
          workspace_id: string;
          inventory_item_id: string;
          movement_type: string;
          quantity: number;
          quantity_before: number;
          quantity_after: number;
          reason: string | null;
          reference_type: string | null;
          reference_id: string | null;
          performed_by: string;
          occurred_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          inventory_item_id: string;
          movement_type: string;
          quantity: number;
          quantity_before: number;
          quantity_after: number;
          reason?: string | null;
          reference_type?: string | null;
          reference_id?: string | null;
          performed_by: string;
          occurred_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          inventory_item_id?: string;
          movement_type?: string;
          quantity?: number;
          quantity_before?: number;
          quantity_after?: number;
          reason?: string | null;
          reference_type?: string | null;
          reference_id?: string | null;
          performed_by?: string;
          occurred_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      purchases: {
        Row: {
          id: string;
          workspace_id: string;
          vendor_id: string;
          purchase_number: string;
          status: string;
          order_date: string | null;
          expected_delivery_date: string | null;
          actual_received_date: string | null;
          currency: string;
          subtotal_minor: number;
          tax_minor: number;
          shipping_minor: number;
          discount_minor: number;
          total_minor: number;
          notes: string | null;
          vendor_reference: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          vendor_id: string;
          purchase_number: string;
          status?: string;
          order_date?: string | null;
          expected_delivery_date?: string | null;
          actual_received_date?: string | null;
          currency?: string;
          subtotal_minor?: number;
          tax_minor?: number;
          shipping_minor?: number;
          discount_minor?: number;
          total_minor?: number;
          notes?: string | null;
          vendor_reference?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          vendor_id?: string;
          purchase_number?: string;
          status?: string;
          order_date?: string | null;
          expected_delivery_date?: string | null;
          actual_received_date?: string | null;
          currency?: string;
          subtotal_minor?: number;
          tax_minor?: number;
          shipping_minor?: number;
          discount_minor?: number;
          total_minor?: number;
          notes?: string | null;
          vendor_reference?: string | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      purchase_items: {
        Row: {
          id: string;
          workspace_id: string;
          purchase_id: string;
          inventory_item_id: string | null;
          name: string;
          sku: string | null;
          quantity_ordered: number;
          quantity_received: number;
          unit_cost_minor: number;
          line_subtotal_minor: number;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          purchase_id: string;
          inventory_item_id?: string | null;
          name: string;
          sku?: string | null;
          quantity_ordered: number;
          quantity_received?: number;
          unit_cost_minor: number;
          line_subtotal_minor: number;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          purchase_id?: string;
          inventory_item_id?: string | null;
          name?: string;
          sku?: string | null;
          quantity_ordered?: number;
          quantity_received?: number;
          unit_cost_minor?: number;
          line_subtotal_minor?: number;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      chart_of_accounts: {
        Row: {
          id: string;
          workspace_id: string;
          account_number: number;
          name: string;
          account_type: string;
          normal_balance: string;
          parent_account_id: string | null;
          description: string | null;
          is_system: boolean;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          account_number: number;
          name: string;
          account_type: string;
          normal_balance: string;
          parent_account_id?: string | null;
          description?: string | null;
          is_system?: boolean;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          account_number?: number;
          name?: string;
          account_type?: string;
          normal_balance?: string;
          parent_account_id?: string | null;
          description?: string | null;
          is_system?: boolean;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      accounting_periods: {
        Row: {
          id: string;
          workspace_id: string;
          period_start: string;
          period_end: string;
          status: string;
          closed_at: string | null;
          closed_by: string | null;
          locked_at: string | null;
          locked_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          period_start: string;
          period_end: string;
          status?: string;
          closed_at?: string | null;
          closed_by?: string | null;
          locked_at?: string | null;
          locked_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          period_start?: string;
          period_end?: string;
          status?: string;
          closed_at?: string | null;
          closed_by?: string | null;
          locked_at?: string | null;
          locked_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      journal_entries: {
        Row: {
          id: string;
          workspace_id: string;
          entry_date: string;
          accounting_period_id: string;
          source_type: string;
          source_id: string | null;
          memo: string | null;
          currency: string;
          reversed_by_entry_id: string | null;
          reverses_entry_id: string | null;
          posting_status: string;
          failure_reason: string | null;
          posted_by: string;
          posting_key: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          entry_date: string;
          accounting_period_id: string;
          source_type: string;
          source_id?: string | null;
          memo?: string | null;
          currency?: string;
          reversed_by_entry_id?: string | null;
          reverses_entry_id?: string | null;
          posting_status?: string;
          failure_reason?: string | null;
          posted_by: string;
          posting_key?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          entry_date?: string;
          accounting_period_id?: string;
          source_type?: string;
          source_id?: string | null;
          memo?: string | null;
          currency?: string;
          reversed_by_entry_id?: string | null;
          reverses_entry_id?: string | null;
          posting_status?: string;
          failure_reason?: string | null;
          posted_by?: string;
          posting_key?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      journal_lines: {
        Row: {
          id: string;
          journal_entry_id: string;
          workspace_id: string;
          account_id: string;
          debit_minor: number;
          credit_minor: number;
          currency: string;
          amount_in_base_currency_minor: number;
          line_memo: string | null;
          line_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          journal_entry_id: string;
          workspace_id: string;
          account_id: string;
          debit_minor?: number;
          credit_minor?: number;
          currency?: string;
          amount_in_base_currency_minor?: number;
          line_memo?: string | null;
          line_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          journal_entry_id?: string;
          workspace_id?: string;
          account_id?: string;
          debit_minor?: number;
          credit_minor?: number;
          currency?: string;
          amount_in_base_currency_minor?: number;
          line_memo?: string | null;
          line_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      stripe_webhook_events: {
        Row: {
          id: string;
          stripe_event_id: string;
          event_type: string;
          workspace_id: string | null;
          payload: Json;
          posting_status: string;
          journal_entry_id: string | null;
          failure_reason: string | null;
          received_at: string;
          processed_at: string | null;
        };
        Insert: {
          id?: string;
          stripe_event_id: string;
          event_type: string;
          workspace_id?: string | null;
          payload: Json;
          posting_status?: string;
          journal_entry_id?: string | null;
          failure_reason?: string | null;
          received_at?: string;
          processed_at?: string | null;
        };
        Update: {
          id?: string;
          stripe_event_id?: string;
          event_type?: string;
          workspace_id?: string | null;
          payload?: Json;
          posting_status?: string;
          journal_entry_id?: string | null;
          failure_reason?: string | null;
          received_at?: string;
          processed_at?: string | null;
        };
        Relationships: [];
      };
      service_categories: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          description: string | null;
          display_order: number;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          description?: string | null;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          description?: string | null;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      services: {
        Row: {
          id: string;
          workspace_id: string;
          category_id: string | null;
          name: string;
          description: string | null;
          status: string;
          draft_version_id: string | null;
          current_published_version_id: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          category_id?: string | null;
          name: string;
          description?: string | null;
          status?: string;
          draft_version_id?: string | null;
          current_published_version_id?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          category_id?: string | null;
          name?: string;
          description?: string | null;
          status?: string;
          draft_version_id?: string | null;
          current_published_version_id?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      service_versions: {
        Row: {
          id: string;
          service_id: string;
          workspace_id: string;
          version_number: number | null;
          status: string;
          name_snapshot: string | null;
          description_snapshot: string | null;
          base_price_minor: number;
          currency: string;
          setup_duration_minutes: number | null;
          breakdown_duration_minutes: number | null;
          difficulty_score: number | null;
          experience_level_required: string | null;
          weather_sensitivity: string;
          surprise_friendly: boolean;
          estimated_profit_minor: number | null;
          change_summary: string | null;
          published_at: string | null;
          published_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          service_id: string;
          workspace_id: string;
          version_number?: number | null;
          status?: string;
          name_snapshot?: string | null;
          description_snapshot?: string | null;
          base_price_minor?: number;
          currency?: string;
          setup_duration_minutes?: number | null;
          breakdown_duration_minutes?: number | null;
          difficulty_score?: number | null;
          experience_level_required?: string | null;
          weather_sensitivity?: string;
          surprise_friendly?: boolean;
          estimated_profit_minor?: number | null;
          change_summary?: string | null;
          published_at?: string | null;
          published_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          service_id?: string;
          workspace_id?: string;
          version_number?: number | null;
          status?: string;
          name_snapshot?: string | null;
          description_snapshot?: string | null;
          base_price_minor?: number;
          currency?: string;
          setup_duration_minutes?: number | null;
          breakdown_duration_minutes?: number | null;
          difficulty_score?: number | null;
          experience_level_required?: string | null;
          weather_sensitivity?: string;
          surprise_friendly?: boolean;
          estimated_profit_minor?: number | null;
          change_summary?: string | null;
          published_at?: string | null;
          published_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      service_included_items: {
        Row: { id: string; workspace_id: string; service_version_id: string; label: string; description: string | null; display_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; service_version_id: string; label: string; description?: string | null; display_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; service_version_id?: string; label?: string; description?: string | null; display_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      service_addons: {
        Row: { id: string; workspace_id: string; service_version_id: string; label: string; description: string | null; price_delta_minor: number; display_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; service_version_id: string; label: string; description?: string | null; price_delta_minor?: number; display_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; service_version_id?: string; label?: string; description?: string | null; price_delta_minor?: number; display_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      service_checklist_template_items: {
        Row: { id: string; workspace_id: string; service_version_id: string; title: string; description: string | null; category: string; priority: string; due_offset_days: number | null; display_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; service_version_id: string; title: string; description?: string | null; category: string; priority: string; due_offset_days?: number | null; display_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; service_version_id?: string; title?: string; description?: string | null; category?: string; priority?: string; due_offset_days?: number | null; display_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      service_timeline_template_items: {
        Row: { id: string; workspace_id: string; service_version_id: string; title: string; description: string | null; category: string; offset_minutes_from_event_start: number; duration_minutes: number | null; display_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; service_version_id: string; title: string; description?: string | null; category: string; offset_minutes_from_event_start: number; duration_minutes?: number | null; display_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; service_version_id?: string; title?: string; description?: string | null; category?: string; offset_minutes_from_event_start?: number; duration_minutes?: number | null; display_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      service_questionnaire_questions: {
        Row: { id: string; workspace_id: string; service_version_id: string; question_text: string; question_type: string; is_required: boolean; options: string[] | null; display_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; service_version_id: string; question_text: string; question_type: string; is_required?: boolean; options?: string[] | null; display_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; service_version_id?: string; question_text?: string; question_type?: string; is_required?: boolean; options?: string[] | null; display_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      service_budget_template_lines: {
        Row: { id: string; workspace_id: string; service_version_id: string; label: string; category: string | null; estimated_revenue_minor: number; estimated_cost_minor: number; display_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; service_version_id: string; label: string; category?: string | null; estimated_revenue_minor?: number; estimated_cost_minor?: number; display_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; service_version_id?: string; label?: string; category?: string | null; estimated_revenue_minor?: number; estimated_cost_minor?: number; display_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      service_approval_template_items: {
        Row: { id: string; workspace_id: string; service_version_id: string; label: string; description: string | null; days_before_event_deadline: number | null; required_role: string | null; display_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; service_version_id: string; label: string; description?: string | null; days_before_event_deadline?: number | null; required_role?: string | null; display_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; service_version_id?: string; label?: string; description?: string | null; days_before_event_deadline?: number | null; required_role?: string | null; display_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      service_travel_template_items: {
        Row: { id: string; workspace_id: string; service_version_id: string; label: string; description: string | null; requires_equipment_transport: boolean; drive_time_buffer_minutes: number | null; mileage_estimate: number | null; display_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; service_version_id: string; label: string; description?: string | null; requires_equipment_transport?: boolean; drive_time_buffer_minutes?: number | null; mileage_estimate?: number | null; display_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; service_version_id?: string; label?: string; description?: string | null; requires_equipment_transport?: boolean; drive_time_buffer_minutes?: number | null; mileage_estimate?: number | null; display_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      service_required_documents: {
        Row: { id: string; workspace_id: string; service_version_id: string; label: string; category: string | null; is_required: boolean; display_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; service_version_id: string; label: string; category?: string | null; is_required?: boolean; display_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; service_version_id?: string; label?: string; category?: string | null; is_required?: boolean; display_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      service_ai_knowledge_items: {
        Row: { id: string; workspace_id: string; service_version_id: string; knowledge_type: string; content: string; severity: string; display_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; service_version_id: string; knowledge_type: string; content: string; severity?: string; display_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; service_version_id?: string; knowledge_type?: string; content?: string; severity?: string; display_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      service_inventory_template_items: {
        Row: { id: string; workspace_id: string; service_version_id: string; inventory_item_id: string | null; item_name: string; quantity: number; display_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; service_version_id: string; inventory_item_id?: string | null; item_name: string; quantity?: number; display_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; service_version_id?: string; inventory_item_id?: string | null; item_name?: string; quantity?: number; display_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      service_purchase_template_items: {
        Row: { id: string; workspace_id: string; service_version_id: string; item_name: string; estimated_unit_cost_minor: number; estimated_quantity: number; typical_vendor_id: string | null; display_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; service_version_id: string; item_name: string; estimated_unit_cost_minor?: number; estimated_quantity?: number; typical_vendor_id?: string | null; display_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; service_version_id?: string; item_name?: string; estimated_unit_cost_minor?: number; estimated_quantity?: number; typical_vendor_id?: string | null; display_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      service_vendor_suggestions: {
        Row: { id: string; workspace_id: string; service_version_id: string; vendor_id: string; note: string | null; display_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; service_version_id: string; vendor_id: string; note?: string | null; display_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; service_version_id?: string; vendor_id?: string; note?: string | null; display_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      service_team_role_requirements: {
        Row: { id: string; workspace_id: string; service_version_id: string; role_label: string; quantity: number; note: string | null; display_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; service_version_id: string; role_label: string; quantity?: number; note?: string | null; display_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; service_version_id?: string; role_label?: string; quantity?: number; note?: string | null; display_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      service_seasonal_windows: {
        Row: { id: string; workspace_id: string; service_version_id: string; start_month: number; end_month: number; note: string | null; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; service_version_id: string; start_month: number; end_month: number; note?: string | null; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; service_version_id?: string; start_month?: number; end_month?: number; note?: string | null; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      service_capability_requirements: {
        Row: { id: string; workspace_id: string; service_version_id: string; capability_type: string; label: string; display_order: number; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; service_version_id: string; capability_type: string; label: string; display_order?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; service_version_id?: string; capability_type?: string; label?: string; display_order?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      event_services: {
        Row: {
          id: string;
          workspace_id: string;
          event_id: string;
          service_id: string;
          service_version_id: string;
          name: string;
          name_template_value: string;
          price_minor: number;
          price_template_value: number;
          currency: string;
          selected_add_on_ids: string[];
          status: string;
          assigned_at: string;
          assigned_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          event_id: string;
          service_id: string;
          service_version_id: string;
          name: string;
          name_template_value: string;
          price_minor?: number;
          price_template_value?: number;
          currency?: string;
          selected_add_on_ids?: string[];
          status?: string;
          assigned_at?: string;
          assigned_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          event_id?: string;
          service_id?: string;
          service_version_id?: string;
          name?: string;
          name_template_value?: string;
          price_minor?: number;
          price_template_value?: number;
          currency?: string;
          selected_add_on_ids?: string[];
          status?: string;
          assigned_at?: string;
          assigned_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      event_service_inventory_requirements: {
        Row: { id: string; workspace_id: string; event_service_id: string; inventory_item_id: string | null; item_name: string; quantity: number; is_fulfilled: boolean; note: string | null; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; event_service_id: string; inventory_item_id?: string | null; item_name: string; quantity?: number; is_fulfilled?: boolean; note?: string | null; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; event_service_id?: string; inventory_item_id?: string | null; item_name?: string; quantity?: number; is_fulfilled?: boolean; note?: string | null; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      event_service_purchase_requirements: {
        Row: { id: string; workspace_id: string; event_service_id: string; item_name: string; estimated_unit_cost_minor: number; estimated_quantity: number; typical_vendor_id: string | null; fulfilled_purchase_id: string | null; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; event_service_id: string; item_name: string; estimated_unit_cost_minor?: number; estimated_quantity?: number; typical_vendor_id?: string | null; fulfilled_purchase_id?: string | null; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; event_service_id?: string; item_name?: string; estimated_unit_cost_minor?: number; estimated_quantity?: number; typical_vendor_id?: string | null; fulfilled_purchase_id?: string | null; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      event_service_budget_lines: {
        Row: { id: string; workspace_id: string; event_service_id: string; label: string; category: string | null; estimated_revenue_minor: number; estimated_cost_minor: number; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; event_service_id: string; label: string; category?: string | null; estimated_revenue_minor?: number; estimated_cost_minor?: number; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; event_service_id?: string; label?: string; category?: string | null; estimated_revenue_minor?: number; estimated_cost_minor?: number; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      event_service_team_requirements: {
        Row: { id: string; workspace_id: string; event_service_id: string; role_label: string; quantity: number; note: string | null; assigned_member_id: string | null; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; event_service_id: string; role_label: string; quantity?: number; note?: string | null; assigned_member_id?: string | null; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; event_service_id?: string; role_label?: string; quantity?: number; note?: string | null; assigned_member_id?: string | null; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      event_service_vendor_assignments: {
        Row: { id: string; workspace_id: string; event_service_id: string; vendor_id: string; status: string; note: string | null; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; event_service_id: string; vendor_id: string; status?: string; note?: string | null; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; event_service_id?: string; vendor_id?: string; status?: string; note?: string | null; created_at?: string; updated_at?: string };
        Relationships: [];
      };
      event_service_questionnaire_responses: {
        Row: { id: string; workspace_id: string; event_service_id: string; question_id: string; response_text: string | null; response_options: string[] | null; response_boolean: boolean | null; response_date: string | null; created_at: string; updated_at: string };
        Insert: { id?: string; workspace_id: string; event_service_id: string; question_id: string; response_text?: string | null; response_options?: string[] | null; response_boolean?: boolean | null; response_date?: string | null; created_at?: string; updated_at?: string };
        Update: { id?: string; workspace_id?: string; event_service_id?: string; question_id?: string; response_text?: string | null; response_options?: string[] | null; response_boolean?: boolean | null; response_date?: string | null; created_at?: string; updated_at?: string };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_workspace_member: {
        Args: { workspace_uuid: string };
        Returns: boolean;
      };
      has_workspace_role: {
        Args: { workspace_uuid: string; allowed_roles: string[] };
        Returns: boolean;
      };
      current_user_workspace_ids: {
        Args: Record<string, never>;
        Returns: string[];
      };
      convert_lead_to_client: {
        Args: { p_lead_id: string; p_actor: string };
        Returns: Json;
      };
      apply_default_event_checklist: {
        Args: { p_event_id: string; p_items: Json; p_description: string; p_actor: string };
        Returns: Json;
      };
      generate_contract_number: {
        Args: { p_workspace_id: string };
        Returns: string;
      };
      generate_invoice_number: {
        Args: { p_workspace_id: string };
        Returns: string;
      };
      recompute_invoice_balance: {
        Args: { p_invoice_id: string; p_actor: string };
        Returns: Database["public"]["Tables"]["invoices"]["Row"];
      };
      process_payment_refund: {
        Args: { p_original_payment_id: string; p_amount_minor: number; p_actor: string };
        Returns: Database["public"]["Tables"]["payments"]["Row"];
      };
      create_document_version: {
        Args: {
          p_document_id: string;
          p_media_asset_id: string | null;
          p_title: string | null;
          p_visibility: string | null;
          p_expires_at_provided: boolean;
          p_expires_at: string | null;
          p_uploaded_by: string | null;
          p_actor: string;
        };
        Returns: Database["public"]["Tables"]["documents"]["Row"];
      };
      apply_default_folder_template: {
        Args: {
          p_workspace_id: string;
          p_owner_type: string;
          p_owner_id: string;
          p_names: string[];
          p_parent_folder_id: string | null;
          p_actor: string;
          p_template_kind: string;
        };
        Returns: Json;
      };
      record_inventory_movement: {
        Args: {
          p_inventory_item_id: string;
          p_movement_type: string;
          p_quantity: number;
          p_reason: string | null;
          p_reference_type: string | null;
          p_reference_id: string | null;
          p_actor: string;
        };
        Returns: Database["public"]["Tables"]["inventory_movements"]["Row"];
      };
      record_purchase_receipt: {
        Args: {
          p_purchase_item_id: string;
          p_quantity_received: number;
          p_reason: string | null;
          p_actor: string;
          p_receipt_event_id: string;
        };
        Returns: Database["public"]["Tables"]["purchase_items"]["Row"];
      };
      finance_resolve_account: {
        Args: { p_workspace_id: string; p_account_number: number };
        Returns: Database["public"]["Tables"]["chart_of_accounts"]["Row"];
      };
      finance_resolve_period: {
        Args: { p_workspace_id: string; p_entry_date: string };
        Returns: string;
      };
      finance_insert_journal_entry: {
        Args: {
          p_workspace_id: string;
          p_entry_date: string;
          p_source_type: string;
          p_source_id: string | null;
          p_memo: string | null;
          p_posted_by: string;
          p_reverses_entry_id: string | null;
          p_posting_key: string | null;
          p_lines: Json;
        };
        Returns: Database["public"]["Tables"]["journal_entries"]["Row"];
      };
      post_purchase_receipt: {
        Args: {
          p_purchase_item_id: string;
          p_quantity_received: number;
          p_receipt_event_id: string;
          p_actor: string;
        };
        Returns: Database["public"]["Tables"]["journal_entries"]["Row"];
      };
      post_payment_settlement: {
        Args: { p_payment_id: string; p_actor: string };
        Returns: Database["public"]["Tables"]["journal_entries"]["Row"];
      };
      record_payment_settlement: {
        Args: {
          p_workspace_id: string;
          p_invoice_id: string | null;
          p_client_id: string;
          p_event_id: string | null;
          p_contract_id: string | null;
          p_payment_type: string;
          p_amount_minor: number;
          p_currency: string;
          p_payment_method: string;
          p_reference: string | null;
          p_transaction_date: string;
          p_notes: string | null;
          p_actor: string;
        };
        Returns: Database["public"]["Tables"]["payments"]["Row"];
      };
      finance_resolve_expense_category_account: {
        Args: { p_workspace_id: string; p_category: string };
        Returns: Database["public"]["Tables"]["chart_of_accounts"]["Row"];
      };
      post_expense_transition: {
        Args: { p_expense_id: string; p_transition: string; p_actor: string };
        Returns: Database["public"]["Tables"]["journal_entries"]["Row"];
      };
      record_expense_transition: {
        Args: { p_expense_id: string; p_transition: string; p_actor: string };
        Returns: Database["public"]["Tables"]["expenses"]["Row"];
      };
      post_inventory_movement_entry: {
        Args: { p_inventory_movement_id: string; p_actor: string };
        Returns: Database["public"]["Tables"]["journal_entries"]["Row"] | null;
      };
      reverse_journal_entry: {
        Args: { p_journal_entry_id: string; p_reason: string; p_actor: string };
        Returns: Database["public"]["Tables"]["journal_entries"]["Row"];
      };
      record_manual_adjustment: {
        Args: {
          p_workspace_id: string;
          p_entry_date: string;
          p_memo: string;
          p_lines: Json;
          p_actor: string;
        };
        Returns: Database["public"]["Tables"]["journal_entries"]["Row"];
      };
      create_accounting_period: {
        Args: {
          p_workspace_id: string;
          p_period_start: string;
          p_period_end: string;
          p_actor: string;
        };
        Returns: Database["public"]["Tables"]["accounting_periods"]["Row"];
      };
      close_period: {
        Args: { p_period_id: string; p_actor: string };
        Returns: Database["public"]["Tables"]["accounting_periods"]["Row"];
      };
      lock_period: {
        Args: { p_period_id: string; p_actor: string };
        Returns: Database["public"]["Tables"]["accounting_periods"]["Row"];
      };
      finance_general_ledger_report: {
        Args: {
          p_workspace_id: string;
          p_start_date: string;
          p_end_date: string;
          p_account_id?: string | null;
          p_account_type?: string | null;
          p_source_type?: string | null;
        };
        Returns: {
          account_id: string;
          account_number: number;
          account_name: string;
          account_type: string;
          normal_balance: string;
          opening_balance_minor: number;
          // journal_entry_id/entry_date/source_type/posting_status/journal_line_id/
          // debit_minor/credit_minor are all null together on the one placeholder
          // row a zero-in-range-activity account gets (see finance_general_
          // ledger_report's own comment) — never independently null otherwise.
          journal_entry_id: string | null;
          entry_date: string | null;
          memo: string | null;
          source_type: string | null;
          source_id: string | null;
          posting_status: string | null;
          journal_line_id: string | null;
          line_memo: string | null;
          debit_minor: number | null;
          credit_minor: number | null;
          running_balance_minor: number;
        }[];
      };
      finance_trial_balance_report: {
        Args: { p_workspace_id: string; p_as_of_date: string; p_include_zero_balances?: boolean };
        Returns: {
          account_id: string;
          account_number: number;
          account_name: string;
          account_type: string;
          normal_balance: string;
          is_archived: boolean;
          total_debit_minor: number;
          total_credit_minor: number;
        }[];
      };
      finance_profit_and_loss_report: {
        Args: {
          p_workspace_id: string;
          p_start_date: string;
          p_end_date: string;
          p_comparison_start_date?: string | null;
          p_comparison_end_date?: string | null;
        };
        Returns: {
          account_id: string;
          account_number: number;
          account_name: string;
          account_type: string;
          normal_balance: string;
          current_debit_minor: number;
          current_credit_minor: number;
          comparison_debit_minor: number;
          comparison_credit_minor: number;
        }[];
      };
      finance_balance_sheet_report: {
        Args: { p_workspace_id: string; p_as_of_date: string };
        Returns: {
          account_id: string;
          account_number: number;
          account_name: string;
          account_type: string;
          parent_account_id: string | null;
          closing_balance_minor: number;
          current_period_earnings_minor: number;
        }[];
      };
      has_permission: {
        Args: { p_workspace_id: string; p_permission: string };
        Returns: boolean;
      };
      get_invitation_by_token: {
        Args: { p_token: string };
        Returns: {
          workspace_name: string;
          email: string;
          invited_role: string;
          status: string;
          expires_at: string;
        }[];
      };
      accept_workspace_invitation: {
        Args: { p_token: string };
        Returns: Database["public"]["Tables"]["workspace_members"]["Row"];
      };
      get_client_invitation_by_token: {
        Args: { p_token: string };
        Returns: {
          workspace_name: string;
          client_name: string;
          email: string;
          status: string;
          expires_at: string;
        }[];
      };
      accept_client_invitation: {
        Args: { p_token: string };
        Returns: Database["public"]["Tables"]["client_accounts"]["Row"];
      };
      is_client_account_holder: {
        Args: { p_client_id: string };
        Returns: boolean;
      };
      get_current_client_account_context: {
        Args: Record<string, never>;
        Returns: {
          account_id: string;
          workspace_name: string;
          client_name: string;
          status: string;
          last_access_at: string | null;
        }[];
      };
      touch_client_account_last_access: {
        Args: Record<string, never>;
        Returns: undefined;
      };
      is_client_account_holder_in_workspace: {
        Args: { p_workspace_id: string; p_client_id: string };
        Returns: boolean;
      };
      get_client_document_storage_ref: {
        Args: { p_document_id: string };
        Returns: {
          storage_bucket: string;
          storage_path: string;
        }[];
      };
      publish_service_version: {
        Args: { p_service_id: string; p_change_summary: string | null; p_actor: string };
        Returns: Database["public"]["Tables"]["service_versions"]["Row"];
      };
      assign_service_to_event: {
        Args: { p_event_id: string; p_service_id: string; p_selected_add_on_ids: string[]; p_actor: string };
        Returns: Database["public"]["Tables"]["event_services"]["Row"];
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
