import type { EntityType } from "@/core/enums/entityType";
import type { ScheduleCategory } from "@/core/enums/scheduleCategory";
import type { ScheduleStatus } from "@/core/enums/scheduleStatus";

/**
 * A reusable schedule item — generalized the same way as ChecklistItem
 * (owner_type/owner_id reusing the shared EntityType union) rather than a
 * plain event_id, so Employee/Vendor/Inventory/Vehicle/Client schedules can
 * reuse this exact table later without a redesign. Only "event" is a real
 * owner today.
 *
 * Same polymorphic-owner caveat as Notes/Timeline/Checklist: owner_id can't
 * carry a normal foreign key, so every query MUST scope by workspace_id
 * together with owner_type/owner_id, never owner_id alone.
 *
 * `source_event_service_id`/`template_snapshot` (Services Foundation phase,
 * Phase 2a) mirror ChecklistItem's own addition exactly — set only for a row
 * generated by an EventService assignment, both null for a manually-created
 * item. `template_snapshot` is the frozen "what the Blueprint originally
 * said" value (e.g. `start_time: "15:00"`); comparing it against this row's
 * own live `start_time` is the entire Event Override mechanism — "Setup
 * starts at 3:00 PM" in the Service Blueprint, overridden to 2:30 PM for one
 * specific Event, with the Blueprint itself never touched.
 */
export interface EventScheduleItemTemplateSnapshot {
  title: string;
  category: ScheduleCategory;
  start_time: string | null;
  end_time: string | null;
}

export interface EventScheduleItem {
  id: string;
  workspace_id: string;
  owner_type: EntityType;
  owner_id: string;
  title: string;
  description: string | null;
  start_time: string | null;
  end_time: string | null;
  location: string | null;
  assigned_to: string | null;
  category: ScheduleCategory;
  status: ScheduleStatus;
  sort_order: number;
  /** Optional — present only on rows generated by an EventService assignment; absent (not just null) on every pre-existing and every manually-created row, so no existing construction site needs updating. */
  source_event_service_id?: string | null;
  template_snapshot?: EventScheduleItemTemplateSnapshot | null;
  created_at: string;
  updated_at: string;
}
