import {
  Play,
  Flag,
  FileCheck,
  FileX,
  CircleDollarSign,
  AlertTriangle,
  FileSignature,
  Newspaper,
  UserCheck,
  TrendingUp,
  BrainCircuit,
  UserCog,
  ToggleLeft,
  Building2,
  DollarSign,
  Tag,
  CalendarClock,
  FileText,
  Users,
  ListTodo,
  Bell,
  Eye,
  RefreshCw,
  ShieldCheck,
  Crown,
  Lock,
  Unlock,
  FileStack,
  Receipt,
  BookOpen,
  ListChecks,
  HelpCircle,
  History,
  CalendarCheck,
  Truck,
  PackageCheck,
  ImagePlus,
  BadgeCheck,
  Store,
  HardHat,
  CalendarPlus,
  Link2,
  Archive,
  Copy,
  Gavel,
  FilePlus,
  FileOutput,
  Hourglass,
  type LucideIcon,
} from "lucide-react";

/**
 * `WorkflowNodeDefinition.icon` is a plain string (never a React component
 * reference — see that field's own doc comment in `types/workflow.ts`), so
 * the Node Registry itself stays importable from server code. This is the
 * one place that string is resolved to a real icon, for the canvas layer's
 * own `NodeRenderer` and the Node Library panel. `HelpCircle` is the
 * fallback for a name not in this map — should only happen for a future
 * node type whose own icon string hasn't been added here yet, never for
 * one of the Step 9 built-ins.
 */
const NODE_ICONS: Record<string, LucideIcon> = {
  Play,
  Flag,
  FileCheck,
  FileX,
  CircleDollarSign,
  AlertTriangle,
  FileSignature,
  Newspaper,
  UserCheck,
  TrendingUp,
  BrainCircuit,
  UserCog,
  ToggleLeft,
  Building2,
  DollarSign,
  Tag,
  CalendarClock,
  FileText,
  Users,
  ListTodo,
  Bell,
  Eye,
  RefreshCw,
  ShieldCheck,
  Crown,
  Lock,
  Unlock,
  FileStack,
  Receipt,
  BookOpen,
  ListChecks,
  History,
  CalendarCheck,
  Truck,
  PackageCheck,
  ImagePlus,
  BadgeCheck,
  Store,
  HardHat,
  CalendarPlus,
  Link2,
  Archive,
  Copy,
  Gavel,
  FilePlus,
  FileOutput,
  Hourglass,
};

export function resolveNodeIcon(name: string): LucideIcon {
  return NODE_ICONS[name] ?? HelpCircle;
}
