import { describe, expect, it } from "vitest";
import { searchHealthToRecommendations, searchHealthRecommendationSource } from "@/core/search/executiveIntegration";
import type { SearchHealthReport } from "@/types/searchHealth";

function makeReport(overrides: Partial<SearchHealthReport> = {}): SearchHealthReport {
  return {
    categories: [
      { category: "coverage", score: 90, issues: [], notApplicableReason: null },
      { category: "index", score: 100, issues: [], notApplicableReason: null },
      { category: "performance", score: null, issues: [], notApplicableReason: "No search-duration data has been recorded yet." },
    ],
    overallScore: 95,
    uncoveredEntityTypes: [],
    recommendations: [],
    evaluatedAt: "2026-06-01T00:00:00.000Z",
    ...overrides,
  };
}

describe("searchHealthToRecommendations", () => {
  it("returns no recommendations when every category has no issues", () => {
    expect(searchHealthToRecommendations(makeReport(), "ws_1")).toEqual([]);
  });

  it("maps each category issue to an OperationalRecommendation with nodeType workspace", () => {
    const report = makeReport({
      categories: [{ category: "coverage", score: 40, issues: ["3 of 30 entity types aren't registered as searchable yet."], notApplicableReason: null }],
    });
    const recommendations = searchHealthToRecommendations(report, "ws_1");
    expect(recommendations).toEqual([
      { ruleId: "search_health_coverage", message: "3 of 30 entity types aren't registered as searchable yet.", severity: "critical", node: { nodeType: "workspace", nodeId: "ws_1" } },
    ]);
  });

  it("severs severity by score: critical below 50, warning below 80, info otherwise", () => {
    const report = makeReport({
      categories: [
        { category: "coverage", score: 40, issues: ["low"], notApplicableReason: null },
        { category: "index", score: 60, issues: ["mid"], notApplicableReason: null },
        { category: "performance", score: 90, issues: ["high"], notApplicableReason: null },
      ],
    });
    const recommendations = searchHealthToRecommendations(report, "ws_1");
    expect(recommendations.map((r) => r.severity)).toEqual(["critical", "warning", "info"]);
  });

  it("treats a null score as info severity", () => {
    const report = makeReport({ categories: [{ category: "performance", score: null, issues: ["stale"], notApplicableReason: null }] });
    expect(searchHealthToRecommendations(report, "ws_1")[0].severity).toBe("info");
  });
});

describe("searchHealthRecommendationSource", () => {
  it("wraps the recommendations in a RecommendationSource generated by search_health_engine", () => {
    const report = makeReport({ categories: [{ category: "coverage", score: 40, issues: ["low"], notApplicableReason: null }] });
    const source = searchHealthRecommendationSource(report, "ws_1");
    expect(source.generatedBy).toBe("search_health_engine");
    expect(source.recommendations).toHaveLength(1);
  });
});
