import { listClientPortalActivityForWorkspace } from "@/lib/data/clientPortal/clientPortalActivityStore";
import { registerMetric } from "@/core/analytics/metricRegistry";
import { buildMetricResult, filterInWindow, groupByDay } from "@/core/analytics/engine";
import type { ClientPortalActivityKind } from "@/types/clientPortalActivity";
import type { MetricComputeContext, MetricComputeResult } from "@/types/analytics";

/**
 * Checkpoint 15 — Portal category metrics. Every one of these is a count
 * over one `ClientPortalActivityKind` from the Client Portal's own
 * Activity log (Checkpoint 14, Step 14's own observability requirement) —
 * the single real source of "what a client did in their Portal session"
 * this codebase has. Never a new tracking mechanism.
 */

function countMetricFor(id: string, name: string, description: string, icon: string, kind: ClientPortalActivityKind) {
  return {
    id,
    name,
    description,
    category: "portal" as const,
    unit: "count" as const,
    icon,
    requiredPermissions: ["clients.portal_view" as const],
    featureFlag: null,
    minimumRole: null,
    refreshPolicy: "realtime" as const,
    async compute(context: MetricComputeContext): Promise<MetricComputeResult> {
      const activity = listClientPortalActivityForWorkspace(context.workspaceId).filter((entry) => entry.kind === kind);
      const dateOf = (entry: (typeof activity)[number]) => entry.occurred_at;
      const current = filterInWindow(activity, dateOf, context.window).length;
      const previous = filterInWindow(activity, dateOf, context.previousWindow).length;
      const series = groupByDay(activity, dateOf, () => 1, context.window);
      return buildMetricResult(current, previous, series);
    },
  };
}

const portalLogins = countMetricFor("portal.logins", "Portal Logins", "Client Portal sign-ins within the selected window.", "LogIn", "login");
const portalDocumentViews = countMetricFor("portal.documentViews", "Document Views", "Documents a client viewed through the Client Portal within the selected window.", "Eye", "document_viewed");
const portalChecklist = countMetricFor("portal.checklistCompletions", "Checklist Completions", "Checklist items a client marked complete within the selected window.", "ListChecks", "checklist_item_completed");
const portalTimeline = countMetricFor("portal.timelineViews", "Timeline Views", "Times a client opened their own Timeline within the selected window.", "History", "timeline_viewed");
const portalNotifications = countMetricFor("portal.notificationReads", "Notifications Read", "Notifications a client marked read within the selected window.", "Bell", "notification_read");
// Checkpoint 36, Step 16 — the remaining 3 of `ClientPortalActivityKind`'s 8 kinds, generated by Centers this checkpoint built (Document Center's download button, Billing Center's invoice view, Communication Center's message composer) but never given their own Portal metric until now.
const portalDocumentDownloads = countMetricFor("portal.documentDownloads", "Document Downloads", "Documents a client downloaded through the Client Portal within the selected window.", "Download", "document_downloaded");
const portalInvoiceViews = countMetricFor("portal.invoiceViews", "Invoice Views", "Invoices a client viewed through the Client Portal within the selected window.", "DollarSign", "invoice_viewed");
const portalMessagesSent = countMetricFor("portal.messagesSent", "Messages Sent", "Messages a client sent through the Client Portal within the selected window.", "Send", "message_sent");

let registered = false;

/** `portal.documentViews` and `documents.views` (`documentMetrics.ts`) deliberately read the same underlying Activity log — the checkpoint's own spec lists "Document views" under both Document Analytics (Step 8) and Portal Analytics (Step 9), the same event framed for two different dashboards. Never a duplicated tracking mechanism, just two thin metric registrations over one source. */
export function registerPortalMetrics(): void {
  if (registered) return;
  registerMetric(portalLogins);
  registerMetric(portalDocumentViews);
  registerMetric(portalChecklist);
  registerMetric(portalTimeline);
  registerMetric(portalNotifications);
  registerMetric(portalDocumentDownloads);
  registerMetric(portalInvoiceViews);
  registerMetric(portalMessagesSent);
  registered = true;
}
