import { getDocumentsManager } from "@/core/documents/manager";
import { resolvePublishedTemplate, mergeContextEntityIdsFromFacts } from "@/modules/documentTemplates/resolvePublishedTemplate";
import type { AutomationActionDefinition, AutomationActionParams, AutomationActionResultDetail, AutomationCategory } from "@/types/automation";
import type { MergeContext } from "@/types/documentPlatform";

interface GenerateDocumentActionSpec {
  id: string;
  name: string;
  description: string;
  documentTypeId: string;
  category: AutomationCategory;
}

/**
 * Step 13/14's own "Documents may be generated by the Automation Engine...
 * never bypass the Automation Engine" — every one of the 5 built-in
 * "Generate X Document" Actions is produced by this one factory, differing
 * only in which document type they resolve a published Template for.
 * Deliberately 5 separate, hardcoded-document-type Actions rather than one
 * generic Action taking a `templateId` parameter: `AutomationActionParams`
 * only ever exposes a trigger's own flat `facts` (Checkpoint 9's own
 * shape) — there is no channel for a Workflow node's own static `data`
 * (e.g. "which Template") to reach an Action at runtime, only the
 * Compiler's own compile-time interpretation of `data` (the same reason
 * "Manager Approval"/"Owner Approval" compile to two different
 * `approvalPolicy` values rather than one Action reading a role parameter).
 * Resolving "the currently published Template for this document type" is
 * the one lookup that needs no such channel at all.
 */
export function makeGenerateDocumentAction(spec: GenerateDocumentActionSpec): AutomationActionDefinition {
  return {
    id: spec.id,
    name: spec.name,
    description: spec.description,
    category: spec.category,
    version: `automation-action-${spec.id}-v1`,
    requiredPermissions: ["documents.create"],
    featureFlag: null,
    minimumRole: null,
    async execute(params: AutomationActionParams): Promise<AutomationActionResultDetail> {
      const template = await resolvePublishedTemplate(params.workspaceId, spec.documentTypeId);
      if (!template) {
        return { success: false, message: `No published "${spec.documentTypeId}" Template exists for this Workspace yet.` };
      }

      const context: MergeContext = {
        workspaceId: params.workspaceId,
        memberId: params.userId ?? "system",
        automationId: params.automationId,
        ...mergeContextEntityIdsFromFacts(params.facts),
      };

      const result = await getDocumentsManager().compileAndCreateDocument(template.id, context, { permissions: params.permissions, role: params.role });
      if (!result.success) {
        return { success: false, message: `Document compile failed: ${result.issues.map((issue) => issue.message).join(" ")}` };
      }

      return { success: true, message: `${spec.name} generated from "${template.name}".` };
    },
  };
}
