import type { Lead } from "@/types/lead";
import type { Client } from "@/types/client";
import type { ProposalDraft } from "@/types/proposal";
import type { Contract } from "@/types/contract";
import type { Invoice } from "@/types/invoice";
import type { Payment } from "@/types/payment";
import type { Event } from "@/types/event";
import type { ClientAccount } from "@/types/clientAccount";
import type { EventFinancialSummary } from "@/modules/finance/financialSummary";

/** v2.0 Checkpoint 32 — shared minimal fixture builders for the Client Journey test suite. Every field a test doesn't care about gets a neutral default; tests override only what they're asserting on. */

export function makeLead(overrides: Partial<Lead> = {}): Lead {
  return {
    id: "lead_1",
    workspace_id: "workspace_1",
    first_name: "Jamie",
    last_name: "Rivera",
    email: "jamie@example.com",
    phone: null,
    instagram: null,
    source: "referral",
    event_type: "wedding",
    event_date: null,
    location: null,
    budget_min: null,
    budget_max: null,
    message: null,
    status: "new",
    assigned_to: null,
    converted_client_id: null,
    created_at: "2026-01-01T00:00:00.000Z",
    updated_at: "2026-01-01T00:00:00.000Z",
    archived_at: null,
    ...overrides,
  };
}

export function makeClient(overrides: Partial<Client> = {}): Client {
  return {
    id: "client_1",
    workspace_id: "workspace_1",
    originating_lead_id: null,
    first_name: "Jamie",
    last_name: "Rivera",
    email: "jamie@example.com",
    phone: "555-0100",
    instagram: null,
    preferred_contact_method: null,
    partner_name: null,
    relationship_status: null,
    important_dates: [],
    address: "123 Main St",
    city: null,
    state: null,
    zip_code: null,
    source: null,
    tags: [],
    internal_status: "active",
    is_returning: false,
    how_they_met: null,
    first_date: null,
    relationship_anniversary: null,
    engagement_date: null,
    wedding_date: null,
    favorite_colors: null,
    favorite_flowers: null,
    favorite_music: null,
    favorite_food: null,
    favorite_drinks: null,
    favorite_restaurants: null,
    preferred_style: null,
    disliked_elements: null,
    allergies: null,
    accessibility_needs: null,
    dietary_restrictions: null,
    preferred_communication_time: null,
    do_not_call: false,
    surprise_event_confidentiality: false,
    emergency_contact_name: null,
    emergency_contact_phone: null,
    is_vip: false,
    created_at: "2026-01-01T00:00:00.000Z",
    updated_at: "2026-01-01T00:00:00.000Z",
    archived_at: null,
    pending_recovery: null,
    ...overrides,
  } as Client;
}

export function makeProposal(overrides: Partial<ProposalDraft> = {}): ProposalDraft {
  return {
    id: "proposal_1",
    workspace_id: "workspace_1",
    event_id: "event_1",
    client_id: "client_1",
    status: "draft",
    version: 1,
    parent_proposal_id: null,
    executive_summary: "",
    event_overview: "",
    services_included: [{ name: "Photography", description: "", price_minor: 100000 }],
    timeline_summary: "",
    pricing_summary: { subtotal_minor: 100000, currency: "usd" },
    payment_terms: [],
    recommendations: [],
    optional_add_ons: [],
    questions_for_client: [],
    ai_confidence: 80,
    missing_information: [],
    provider: "mock",
    model: "mock",
    prompt_version: "1",
    mock: true,
    generation_latency_ms: 0,
    generated_at: "2026-01-02T00:00:00.000Z",
    reviewed_by: null,
    reviewed_at: null,
    created_at: "2026-01-02T00:00:00.000Z",
    updated_at: "2026-01-02T00:00:00.000Z",
    ...overrides,
  } as ProposalDraft;
}

export function makeContract(overrides: Partial<Contract> = {}): Contract {
  return {
    id: "contract_1",
    workspace_id: "workspace_1",
    client_id: "client_1",
    event_id: "event_1",
    template_id: null,
    contract_number: "C-1",
    title: "Wedding Contract",
    description: "Standard wedding services contract",
    status: "draft",
    signature_status: "unsigned",
    version: 1,
    version_history: [],
    effective_date: null,
    expiration_date: null,
    signed_at: null,
    sent_at: null,
    viewed_at: null,
    declined_at: null,
    cancelled_at: null,
    archived_at: null,
    total_value: 10000,
    deposit_required: true,
    deposit_amount: 2000,
    remaining_balance: 8000,
    currency: "usd",
    notes: null,
    created_at: "2026-01-03T00:00:00.000Z",
    updated_at: "2026-01-03T00:00:00.000Z",
    ...overrides,
  } as Contract;
}

export function makeInvoice(overrides: Partial<Invoice> = {}): Invoice {
  return {
    id: "invoice_1",
    workspace_id: "workspace_1",
    client_id: "client_1",
    event_id: "event_1",
    contract_id: "contract_1",
    invoice_number: "INV-1",
    title: "Deposit Invoice",
    description: null,
    status: "draft",
    issue_date: "2026-01-04",
    due_date: "2026-01-18",
    subtotal_minor: 200000,
    tax_minor: 0,
    discount_minor: 0,
    total_minor: 200000,
    paid_minor: 0,
    balance_minor: 200000,
    currency: "usd",
    notes: null,
    sent_at: null,
    viewed_at: null,
    paid_at: null,
    overdue_at: null,
    voided_at: null,
    archived_at: null,
    created_at: "2026-01-04T00:00:00.000Z",
    updated_at: "2026-01-04T00:00:00.000Z",
    ...overrides,
  } as Invoice;
}

export function makePayment(overrides: Partial<Payment> = {}): Payment {
  return {
    id: "payment_1",
    workspace_id: "workspace_1",
    invoice_id: "invoice_1",
    client_id: "client_1",
    event_id: "event_1",
    contract_id: "contract_1",
    payment_type: "deposit",
    status: "succeeded",
    amount_minor: 200000,
    currency: "usd",
    payment_method: null,
    reference: null,
    transaction_date: "2026-01-05T00:00:00.000Z",
    received_at: "2026-01-05T00:00:00.000Z",
    failed_at: null,
    refunded_at: null,
    notes: null,
    document_id: null,
    created_at: "2026-01-05T00:00:00.000Z",
    updated_at: "2026-01-05T00:00:00.000Z",
    ...overrides,
  } as Payment;
}

export function makeEvent(overrides: Partial<Event> = {}): Event {
  return {
    id: "event_1",
    workspace_id: "workspace_1",
    client_id: "client_1",
    originating_lead_id: null,
    title: "Rivera Wedding",
    event_type: "wedding",
    status: "planning",
    lifecycle_stage: "planning",
    event_date: "2026-06-01",
    start_time: null,
    end_time: null,
    timezone: null,
    location_name: null,
    address: null,
    city: null,
    state: null,
    zip_code: null,
    latitude: null,
    longitude: null,
    guest_count: 100,
    budget_min: null,
    budget_max: null,
    package_name: null,
    theme: null,
    color_palette: null,
    surprise_event: false,
    confidentiality_notes: null,
    accessibility_notes: null,
    dietary_notes: null,
    weather_plan: null,
    backup_location: null,
    internal_summary: null,
    assigned_owner: null,
    priority: "medium",
    created_at: "2026-01-01T00:00:00.000Z",
    updated_at: "2026-01-01T00:00:00.000Z",
    archived_at: null,
    completed_at: null,
    cancelled_at: null,
    ...overrides,
  } as Event;
}

export function makeClientAccount(overrides: Partial<ClientAccount> = {}): ClientAccount {
  return {
    id: "clientaccount_1",
    workspace_id: "workspace_1",
    client_id: "client_1",
    auth_user_id: "user_1",
    email: "jamie@example.com",
    status: "active",
    invited_by: null,
    accepted_at: "2026-01-06T00:00:00.000Z",
    suspended_at: null,
    revoked_at: null,
    last_access_at: null,
    created_at: "2026-01-06T00:00:00.000Z",
    updated_at: "2026-01-06T00:00:00.000Z",
    ...overrides,
  } as ClientAccount;
}

export function makeFinancialSummary(overrides: Partial<EventFinancialSummary> = {}): EventFinancialSummary {
  return {
    contracted_value_minor: 1000000,
    invoiced_total_minor: 200000,
    collected_minor: 0,
    refunded_minor: 0,
    outstanding_minor: 200000,
    expense_total_minor: 0,
    gross_profit_minor: 200000,
    net_profit_minor: 0,
    deposit_required_minor: 200000,
    deposit_paid_minor: 0,
    deposit_balance_minor: 200000,
    payment_completion_percentage: 0,
    expense_percentage_of_revenue: 0,
    ...overrides,
  };
}
