-- Services migration 10: Instance-layer requirement/estimate child tables —
-- event_service_inventory_requirements, event_service_purchase_requirements,
-- event_service_budget_lines, event_service_team_requirements.
--
-- Mirror src/types/eventServiceInventoryRequirement.ts,
-- eventServicePurchaseRequirement.ts, eventServiceBudgetLine.ts,
-- eventServiceTeamRequirement.ts exactly. All four are generated by
-- assign_service_to_event from the pinned ServiceVersion's matching
-- template rows (computeServiceRequirements) — none of these tables is
-- ever written to by anything else at generation time.
--
-- None of these ever auto-mutates a real ledger: is_fulfilled/
-- fulfilled_purchase_id are set by a human explicitly linking a real
-- Inventory movement/Purchase afterward, never automatically.

create table if not exists public.event_service_inventory_requirements (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  event_service_id uuid not null references public.event_services (id) on delete cascade,
  inventory_item_id uuid references public.inventory_items (id) on delete set null,
  item_name text not null,
  quantity integer not null default 1,
  is_fulfilled boolean not null default false,
  note text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint event_service_inventory_requirements_item_name_check check (btrim(item_name) <> ''),
  constraint event_service_inventory_requirements_quantity_check check (quantity > 0)
);

comment on table public.event_service_inventory_requirements is
  'Generated from service_inventory_template_items at assignment — "this Event needs N of X." Never decrements real Inventory itself; is_fulfilled is a human-set flag once the need is met via a real record_inventory_movement call. See docs/services.md.';

create table if not exists public.event_service_purchase_requirements (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  event_service_id uuid not null references public.event_services (id) on delete cascade,
  item_name text not null,
  estimated_unit_cost_minor integer not null default 0,
  estimated_quantity integer not null default 1,
  typical_vendor_id uuid references public.vendors (id) on delete set null,
  fulfilled_purchase_id uuid references public.purchases (id) on delete set null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint event_service_purchase_requirements_item_name_check check (btrim(item_name) <> ''),
  constraint event_service_purchase_requirements_unit_cost_check check (estimated_unit_cost_minor >= 0),
  constraint event_service_purchase_requirements_quantity_check check (estimated_quantity > 0)
);

comment on table public.event_service_purchase_requirements is
  'Generated from service_purchase_template_items at assignment — a draft a human reviews and turns into a real Purchase; fulfilled_purchase_id is set once that happens. Never creates a real Purchase automatically. See docs/services.md.';

create table if not exists public.event_service_budget_lines (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  event_service_id uuid not null references public.event_services (id) on delete cascade,
  label text not null,
  category text,
  estimated_revenue_minor integer not null default 0,
  estimated_cost_minor integer not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint event_service_budget_lines_label_not_blank_check check (btrim(label) <> ''),
  constraint event_service_budget_lines_estimated_revenue_check check (estimated_revenue_minor >= 0),
  constraint event_service_budget_lines_estimated_cost_check check (estimated_cost_minor >= 0)
);

comment on table public.event_service_budget_lines is
  'Generated from service_budget_template_lines at assignment — a forward-looking estimate for a future "Estimated Budget" view, deliberately separate from Finance''s real, ledger-derived EventFinancialSummary. See docs/services.md.';

create table if not exists public.event_service_team_requirements (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  event_service_id uuid not null references public.event_services (id) on delete cascade,
  role_label text not null,
  quantity integer not null default 1,
  note text,
  assigned_member_id uuid,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint event_service_team_requirements_role_label_check check (btrim(role_label) <> ''),
  constraint event_service_team_requirements_quantity_check check (quantity > 0)
);

comment on table public.event_service_team_requirements is
  'Generated from service_team_role_requirements at assignment. assigned_member_id has no FK yet — reserved for the future Team Operations module, matching inventory_items.primary_vendor_id''s original precedent. See docs/services.md.';
