-- Services migration 13: add source_event_service_id + template_snapshot to
-- checklist_items and event_schedule_items.
--
-- Mirrors the optional fields added to src/types/checklistItem.ts and
-- eventScheduleItem.ts exactly. Both columns are nullable and set only for
-- a row generated by an EventService assignment — every pre-existing and
-- every manually-created row keeps both null, so no existing data or code
-- path is affected. This is the entire mechanism by which multiple
-- assigned Services' generated items coexist in the same tables real
-- Checklist/Schedule already used, and by which the Event Override
-- strategy is implemented — see docs/services.md's "Multi-Service
-- coexistence and the override mechanism" and "Snapshot Review" sections.
--
-- template_snapshot is jsonb (not a second set of typed columns) since its
-- shape differs between the two tables (title/category/priority/due_date
-- vs. title/category/start_time/end_time) and it is never queried or
-- filtered on — only ever read back whole, for a UI comparison against the
-- row's own live fields.
--
-- on delete set null (not cascade): an EventService is never hard-deleted
-- by this application (removeEventService only ever deletes the specific
-- generated rows it's responsible for, never the EventService's siblings),
-- but this is the same defensive "if it ever were" clause
-- purchase_items.inventory_item_id already uses.

alter table public.checklist_items
  add column if not exists source_event_service_id uuid references public.event_services (id) on delete set null,
  add column if not exists template_snapshot jsonb;

alter table public.event_schedule_items
  add column if not exists source_event_service_id uuid references public.event_services (id) on delete set null,
  add column if not exists template_snapshot jsonb;

comment on column public.checklist_items.source_event_service_id is
  'Set only for a row generated by assign_service_to_event — null for every manually-created item. See docs/services.md.';
comment on column public.checklist_items.template_snapshot is
  'Frozen copy of {title, category, priority, due_date} as originally generated from the Service template — the Event Override comparison baseline. Null unless source_event_service_id is set.';
comment on column public.event_schedule_items.source_event_service_id is
  'Set only for a row generated by assign_service_to_event — null for every manually-created item. See docs/services.md.';
comment on column public.event_schedule_items.template_snapshot is
  'Frozen copy of {title, category, start_time, end_time} as originally generated from the Service template — the Event Override comparison baseline. Null unless source_event_service_id is set.';
